import type { CalendarEvent } from "@/types/calendarEvent";

// Mocked "heute" passend zu den Proben-/Prüfwerte-Mockdaten dieser Sprints.
export const HEUTE = "03.03.2026";

export const weekDates = [
  "02.03.2026",
  "03.03.2026",
  "04.03.2026",
  "05.03.2026",
  "06.03.2026",
  "07.03.2026",
  "08.03.2026",
];

export const weekDayLabels = ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"];

export const calendarEvents: CalendarEvent[] = [
  {
    id: "cal-01",
    title: "Kalibrierung Druckprüfmaschine",
    date: "02.03.2026",
    time: "08:30",
    duration: "30 min",
    field: "Sonstiges",
    status: "geplant",
    description: "Jährliche Kalibrierung der Druckprüfmaschine im Betonlabor.",
  },
  {
    id: "cal-02",
    title: "Sieblinie ASP-2026-007",
    date: "02.03.2026",
    time: "11:00",
    duration: "45 min",
    field: "Asphalt",
    status: "abgeschlossen",
    sampleId: "ASP-2026-007",
    bezeichnung: "Asphaltmischgut",
    projekt: "L 342 Fahrbahnerneuerung",
    kunde: "Straßenbau Nord",
    pruefer: "S. Wolf",
    description: "Siebanalyse zur Bestimmung der Korngrößenverteilung des Asphaltmischguts.",
  },
  {
    id: "cal-03",
    title: "28-Tage-Prüfung BET-2026-014",
    date: "03.03.2026",
    time: "09:00",
    duration: "60 min",
    field: "Beton",
    status: "in Arbeit",
    priority: "hoch",
    sampleId: "BET-2026-014",
    bezeichnung: "Beton C25/30",
    projekt: "Neubau Wohnanlage",
    kunde: "Musterbau GmbH",
    pruefer: "A. Meier",
    description: "Druckfestigkeitsprüfung der Betonwürfel nach 28 Tagen Nachbehandlung.",
  },
  {
    id: "cal-04",
    title: "7-Tage-Prüfung PR-2026-008",
    date: "03.03.2026",
    time: "10:30",
    duration: "45 min",
    field: "Beton",
    status: "geplant",
    sampleId: "PR-2026-008",
    bezeichnung: "Betonprisma",
    projekt: "Brückensanierung B17",
    kunde: "Baresel AG",
    pruefer: "T. Keller",
    description: "Biegezug- und Druckfestigkeitsprüfung am Betonprisma nach 7 Tagen.",
  },
  {
    id: "cal-05",
    title: "Proctor-Versuch GEO-2026-021",
    date: "03.03.2026",
    time: "13:00",
    duration: "90 min",
    field: "Geotechnik",
    status: "überfällig",
    priority: "hoch",
    sampleId: "GEO-2026-021",
    bezeichnung: "Bodenprobe Sand",
    projekt: "Baugebiet Nord",
    kunde: "Musterbau GmbH",
    pruefer: "A. Meier",
    description: "Ermittlung von Proctordichte und optimalem Wassergehalt der Bodenprobe.",
  },
  {
    id: "cal-06",
    title: "Laborbericht prüfen",
    date: "03.03.2026",
    time: "16:00",
    duration: "30 min",
    field: "Sonstiges",
    status: "geplant",
    description: "Prüfberichte der Woche gegenlesen und freigeben.",
  },
  {
    id: "cal-07",
    title: "Asphaltbohrkern ASP-2026-011",
    date: "04.03.2026",
    time: "15:00",
    duration: "60 min",
    field: "Asphalt",
    status: "in Arbeit",
    sampleId: "ASP-2026-011",
    bezeichnung: "Asphaltbohrkern",
    projekt: "L 342 Fahrbahnerneuerung",
    kunde: "Straßenbau Nord",
    pruefer: "S. Wolf",
    description: "Marshall-Prüfung zur Bestimmung von Stabilität und Fließwert.",
  },
  {
    id: "cal-08",
    title: "Wareneingang Zementproben",
    date: "05.03.2026",
    time: "09:30",
    duration: "20 min",
    field: "Sonstiges",
    status: "geplant",
    description: "Neue Zementproben annehmen und einlagern.",
  },
  {
    id: "cal-09",
    title: "Laborbesprechung Wochenrückblick",
    date: "06.03.2026",
    time: "10:00",
    duration: "30 min",
    field: "Sonstiges",
    status: "geplant",
    description: "Wöchentliche Abstimmung im Laborteam zu offenen Prüfungen.",
  },
];
