import type { Customer } from "@/types/customer";

// Mock-Daten für die Kundenverwaltung (/kunden). Eigenständiger Datensatz,
// keine Firebase-Anbindung. Projekt- und Kundennamen bewusst konsistent mit
// den Mock-Projekten aus config/projects.ts gehalten, damit sich beide
// Bereiche später sauber verknüpfen lassen.

export const customers: Customer[] = [
  {
    id: "cust-musterbau",
    name: "Musterbau GmbH",
    number: "K-2026-001",
    type: "Bauunternehmen",
    status: "Aktiv",
    contactPerson: "Max Mustermann",
    contactPersonInitials: "MM",
    email: "max.mustermann@musterbau.de",
    phone: "+49 711 998877",
    street: "Parkstraße 15",
    postalCode: "70190",
    city: "Stuttgart",
    country: "Deutschland",
    vatId: "DE 987654321",
    website: "www.musterbau.de",
    projects: ["Neubau Wohnanlage Parkblick", "Baugebiet Nord"],
    invoices: [
      { id: "rg-001", title: "RG-2026-001 Prüfbericht Beton", date: "20.01.2026" },
      { id: "rg-002", title: "RG-2026-002 Baustellenprüfung", date: "05.02.2026" },
      { id: "rg-003", title: "RG-2026-003 Asphaltprüfung", date: "18.02.2026" },
    ],
    deliveryNotes: [
      { id: "ls-c-001", title: "LS-2026-001 Betonlieferung", date: "20.01.2026" },
      { id: "ls-c-002", title: "LS-2026-002 Zusatzmittel", date: "28.01.2026" },
      { id: "ls-c-003", title: "LS-2026-003 Asphaltmischgut", date: "05.02.2026" },
    ],
    documentsCount: 11,
    history: [
      { message: "Kunde angelegt.", timestamp: "10.01.2026" },
      { message: 'Projekt „Neubau Wohnanlage Parkblick" verknüpft.', timestamp: "15.01.2026" },
      { message: "Rechnung RG-2026-001 hinzugefügt.", timestamp: "20.01.2026" },
    ],
  },
  {
    id: "cust-baresel",
    name: "Baresel AG",
    number: "K-2026-002",
    type: "Bauunternehmen",
    status: "Aktiv",
    contactPerson: "Julia Baresel",
    contactPersonInitials: "JB",
    email: "julia.baresel@baresel.de",
    phone: "+49 7146 55210",
    street: "Neckarstraße 8",
    postalCode: "71686",
    city: "Remseck",
    country: "Deutschland",
    vatId: "DE 456789123",
    website: "www.baresel.de",
    projects: ["Brückensanierung B17"],
    invoices: [{ id: "rg-004", title: "RG-2026-004 Prüfbericht Brücke", date: "10.02.2026" }],
    deliveryNotes: [{ id: "ls-c-004", title: "LS-2026-004 Asphaltmischgut", date: "10.02.2026" }],
    documentsCount: 4,
    history: [{ message: "Kunde angelegt.", timestamp: "25.01.2026" }],
  },
  {
    id: "cust-strassenbau-nord",
    name: "Straßenbau Nord",
    number: "K-2026-003",
    type: "Behörde",
    status: "Aktiv",
    contactPerson: "Thomas Weber",
    contactPersonInitials: "TW",
    email: "thomas.weber@strassenbau-nord.de",
    phone: "+49 5121 44120",
    street: "Industrieweg 3",
    postalCode: "71634",
    city: "Ludwigsburg",
    country: "Deutschland",
    projects: ["L 342 Fahrbahnerneuerung"],
    invoices: [],
    deliveryNotes: [{ id: "ls-c-005", title: "LS-2026-005 Asphaltmischgut", date: "14.02.2026" }],
    documentsCount: 3,
    history: [{ message: "Kunde angelegt.", timestamp: "08.02.2026" }],
  },
  {
    id: "cust-industriebau-sued",
    name: "Industriebau Süd GmbH",
    number: "K-2026-004",
    type: "Industriekunde",
    status: "Aktiv",
    contactPerson: "Miriam Koch",
    contactPersonInitials: "MK",
    email: "miriam.koch@industriebau-sued.de",
    phone: "+49 731 22110",
    street: "Gewerbepark Ost 7",
    postalCode: "89073",
    city: "München",
    country: "Deutschland",
    vatId: "DE 112233445",
    website: "www.industriebau-sued.de",
    projects: ["Gewerbepark Ost"],
    invoices: [{ id: "rg-005", title: "RG-2026-005 Abschlussbericht Gewerbepark", date: "22.12.2025" }],
    deliveryNotes: [{ id: "ls-c-006", title: "LS-2025-118 Betonlieferung", date: "15.11.2025" }],
    documentsCount: 14,
    history: [
      { message: "Kunde angelegt.", timestamp: "01.06.2025" },
      { message: 'Projekt „Gewerbepark Ost" abgeschlossen.', timestamp: "20.12.2025" },
    ],
  },
  {
    id: "cust-privat-schneider",
    name: "Privatkunde Schneider",
    number: "K-2026-005",
    type: "Privatkunde",
    status: "Inaktiv",
    contactPerson: "Laura Schneider",
    contactPersonInitials: "LS",
    email: "laura.schneider@privat.de",
    phone: "+49 711 5544332",
    street: "Gartenweg 4",
    postalCode: "70199",
    city: "Stuttgart",
    country: "Deutschland",
    projects: [],
    invoices: [],
    deliveryNotes: [],
    documentsCount: 1,
    history: [
      { message: "Kunde angelegt.", timestamp: "05.09.2025" },
      { message: "Kunde deaktiviert.", timestamp: "30.11.2025" },
    ],
  },
];
