import type { Device } from "@/types/device";

// Mock-Daten für die Geräteverwaltung (/geraete). Eigenständiger Datensatz,
// keine Firebase-Anbindung. Standorte bewusst konsistent mit den
// Mock-Standorten aus config/locations.ts gehalten.

export const devices: Device[] = [
  {
    id: "dev-dr-001",
    inventoryNumber: "DR-001",
    name: "Druckprüfpresse",
    type: "Druckpresse",
    manufacturer: "ToniTechnik",
    model: "Presse 3000",
    serialNumber: "TT-3000-2022-014",
    yearBuilt: "2022",
    location: "Labor Stuttgart",
    locationId: "loc-stuttgart",
    status: "Einsatzbereit",
    responsiblePerson: "Anna Neumann",
    responsiblePersonInitials: "AN",
    lastCalibration: "15.09.2025",
    nextCalibration: "15.09.2026",
    calibrationCertificate: "Kalibrierschein-DR-001-2025.pdf",
    lastMaintenance: "10.01.2026",
    nextMaintenance: "10.07.2026",
    maintenanceInterval: "6 Monate",
    documents: [
      { id: "doc-dr-1", title: "Bedienungsanleitung.pdf", date: "01.03.2022" },
      { id: "doc-dr-2", title: "Kalibrierschein.pdf", date: "15.09.2025" },
      { id: "doc-dr-3", title: "Wartungsprotokoll.pdf", date: "10.01.2026" },
    ],
    history: [
      { message: "Gerät angelegt.", timestamp: "01.03.2022" },
      { message: "Kalibrierung dokumentiert.", timestamp: "15.09.2025" },
      { message: "Wartung dokumentiert.", timestamp: "10.01.2026" },
    ],
  },
  {
    id: "dev-wa-014",
    inventoryNumber: "WA-014",
    name: "Präzisionswaage",
    type: "Waage",
    manufacturer: "Sartorius",
    model: "Entris",
    serialNumber: "SAR-ENT-2021-089",
    yearBuilt: "2021",
    location: "Labor München",
    locationId: "loc-muenchen",
    status: "Kalibrierung fällig",
    responsiblePerson: "Tom Müller",
    responsiblePersonInitials: "TM",
    lastCalibration: "20.02.2025",
    nextCalibration: "20.02.2026",
    calibrationCertificate: "Kalibrierschein-WA-014-2025.pdf",
    lastMaintenance: "05.08.2025",
    nextMaintenance: "05.08.2026",
    maintenanceInterval: "12 Monate",
    documents: [
      { id: "doc-wa-1", title: "Bedienungsanleitung.pdf", date: "10.05.2021" },
      { id: "doc-wa-2", title: "Kalibrierschein.pdf", date: "20.02.2025" },
    ],
    history: [
      { message: "Gerät angelegt.", timestamp: "10.05.2021" },
      { message: "Kalibrierung ist überfällig.", timestamp: "20.02.2026" },
    ],
  },
  {
    id: "dev-ks-002",
    inventoryNumber: "KS-002",
    name: "Klimaschrank",
    type: "Klimaschrank",
    manufacturer: "Memmert",
    model: "HPP 110",
    serialNumber: "MEM-HPP110-2020-045",
    yearBuilt: "2020",
    location: "Labor Stuttgart",
    locationId: "loc-stuttgart",
    status: "Wartung fällig",
    responsiblePerson: "Max Mustermann",
    responsiblePersonInitials: "MM",
    lastCalibration: "12.11.2025",
    nextCalibration: "12.11.2026",
    lastMaintenance: "01.09.2025",
    nextMaintenance: "01.03.2026",
    maintenanceInterval: "6 Monate",
    documents: [{ id: "doc-ks-1", title: "Bedienungsanleitung.pdf", date: "20.02.2020" }],
    history: [
      { message: "Gerät angelegt.", timestamp: "20.02.2020" },
      { message: "Wartung ist überfällig.", timestamp: "01.03.2026" },
    ],
  },
  {
    id: "dev-si-011",
    inventoryNumber: "SI-011",
    name: "Siebmaschine",
    type: "Siebanlage",
    manufacturer: "Retsch",
    model: "AS 200",
    serialNumber: "RET-AS200-2019-011",
    yearBuilt: "2019",
    location: "Labor Remseck",
    locationId: "loc-remseck",
    status: "Außer Betrieb",
    responsiblePerson: "S. Wolf",
    responsiblePersonInitials: "SW",
    lastCalibration: "18.06.2025",
    nextCalibration: "18.06.2026",
    lastMaintenance: "18.06.2025",
    nextMaintenance: "18.06.2026",
    maintenanceInterval: "12 Monate",
    notes: "Antriebsmotor defekt, Ersatzteil bestellt.",
    documents: [{ id: "doc-si-1", title: "Bedienungsanleitung.pdf", date: "05.03.2019" }],
    history: [
      { message: "Gerät angelegt.", timestamp: "05.03.2019" },
      { message: "Außer Betrieb gesetzt: Antriebsmotor defekt.", timestamp: "20.02.2026" },
    ],
  },
  {
    id: "dev-tr-005",
    inventoryNumber: "TR-005",
    name: "Trockenschrank",
    type: "Trockenschrank",
    manufacturer: "Binder",
    model: "FD 115",
    serialNumber: "BIN-FD115-2018-005",
    yearBuilt: "2018",
    location: "Baustellenbüro Nord",
    locationId: "loc-baustelle-nord",
    status: "Archiviert",
    lastCalibration: "10.01.2024",
    nextCalibration: "10.01.2025",
    lastMaintenance: "10.01.2024",
    nextMaintenance: "10.01.2025",
    maintenanceInterval: "12 Monate",
    notes: "Außer Dienst gestellt, durch neues Gerät ersetzt.",
    documents: [{ id: "doc-tr-1", title: "Bedienungsanleitung.pdf", date: "15.04.2018" }],
    history: [
      { message: "Gerät angelegt.", timestamp: "15.04.2018" },
      { message: "Gerät archiviert.", timestamp: "01.02.2026" },
    ],
  },
];
