import { Building2, Layers, Mountain } from "lucide-react";

import { normDisclaimer } from "@/config/learning";
import type { CalculatorDefinition, FieldAreaConfig, FieldAreaId, FieldAreaProcedure } from "@/types/fieldArea";
import type { Formula, GlossaryTerm, NormReference } from "@/types/learning";

export { normDisclaimer };

function parseNumber(value: string): number {
  return parseFloat(value.replace(",", "."));
}

function average(values: string[]): number | null {
  const numbers = values.map(parseNumber).filter((n) => !Number.isNaN(n));
  if (numbers.length === 0) return null;
  return numbers.reduce((sum, n) => sum + n, 0) / numbers.length;
}

// =============================================================
// Beton
// =============================================================

const betonProcedures: FieldAreaProcedure[] = [
  {
    id: "beton-ausbreitmass",
    title: "Ausbreitmaß",
    category: "Frischbeton",
    shortDescription: "Konsistenz des Frischbetons durch Ausbreiten auf dem Ausbreittisch bestimmen.",
    location: "Labor & Baustelle",
    status: "Verfügbar",
    tags: ["Labor", "Baustelle", "Frischzustand"],
    favorite: true,
    learned: true,
    purpose: "Ermittlung der Konsistenzklasse (F1–F6) zur Beurteilung der Verarbeitbarkeit von Frischbeton.",
    equipment: ["Ausbreittisch", "Setztrichter", "Stopfer", "Kelle"],
    preparation: ["Ausbreittisch und Trichter befeuchten", "Frischbeton in zwei Lagen einfüllen und verdichten"],
    steps: ["Trichter senkrecht anheben", "Tischplatte 15-mal in 15 s anheben und fallen lassen", "Zwei Durchmesser rechtwinklig messen"],
    inputs: ["Durchmesser d1 (mm)", "Durchmesser d2 (mm)"],
    outputs: ["Ausbreitmaß a (mm)", "Konsistenzklasse"],
    pitfalls: ["Ungleichmäßige Verdichtung der Lagen", "Ausbreittisch nicht eben aufgestellt", "Messung zu spät nach Herstellung"],
    normHint: "Orientierung an DIN EN 12350-5.",
  },
  {
    id: "beton-setzmass",
    title: "Setzmaß",
    category: "Frischbeton",
    shortDescription: "Konsistenz des Frischbetons über das Absacken des Betonkegels (Slump-Test).",
    location: "Labor & Baustelle",
    status: "Verfügbar",
    tags: ["Labor", "Baustelle", "Frischzustand"],
    favorite: false,
    learned: true,
    purpose: "Bestimmung der Konsistenzklasse (S1–S5) anhand des Setzmaßes.",
    equipment: ["Setztrichter (Abrams-Kegel)", "Stopfer", "Messlatte"],
    preparation: ["Trichter auf feuchter, ebener Unterlage aufstellen", "Beton in drei Lagen einfüllen und verdichten"],
    steps: ["Trichter langsam senkrecht abziehen", "Höhenunterschied zum Trichter messen"],
    inputs: ["Kegelhöhe (mm)", "Setzmaß (mm)"],
    outputs: ["Setzmaß s (mm)", "Konsistenzklasse"],
    pitfalls: ["Trichter zu schnell abgezogen", "Unterlage nicht eben", "Abscheren statt gleichmäßigem Setzen"],
    normHint: "Orientierung an DIN EN 12350-2.",
  },
  {
    id: "beton-luftgehalt",
    title: "Luftgehalt",
    category: "Frischbeton",
    shortDescription: "Luftporengehalt im Frischbeton mit dem Druckausgleichsverfahren bestimmen.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Baustelle", "Frischzustand"],
    favorite: false,
    learned: false,
    purpose: "Kontrolle des künstlich eingeführten Luftporengehalts für den Frost-Tau-Widerstand.",
    equipment: ["Luftgehaltsprüfer (Drucktopf)", "Stopfer", "Kelle"],
    preparation: ["Topf in drei Lagen mit Beton befüllen und verdichten", "Deckel dicht verschließen"],
    steps: ["Wasser bis Markierung einfüllen", "Druck aufbauen und Ventile öffnen", "Luftgehalt am Manometer ablesen"],
    inputs: ["Manometerdruck (bar)"],
    outputs: ["Luftgehalt (Vol.-%)"],
    pitfalls: ["Undichter Deckel", "Nicht kalibriertes Gerät", "Grobe Gesteinskörnung verfälscht Ergebnis"],
    normHint: "Orientierung an DIN EN 12350-7.",
  },
  {
    id: "beton-frischbetonrohdichte",
    title: "Frischbetonrohdichte",
    category: "Frischbeton",
    shortDescription: "Rohdichte des verdichteten Frischbetons je Volumeneinheit bestimmen.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Frischzustand"],
    favorite: false,
    learned: false,
    purpose: "Ermittlung der Frischbetonrohdichte als Qualitäts- und Rezepturkennwert.",
    equipment: ["Messbehälter (bekanntes Volumen)", "Waage", "Stopfer"],
    preparation: ["Messbehälter tarieren", "Beton in Lagen einfüllen und verdichten"],
    steps: ["Behälter randvoll abziehen", "Masse des befüllten Behälters wiegen", "Rohdichte berechnen"],
    inputs: ["Masse befüllter Behälter (kg)", "Behältervolumen (m³)"],
    outputs: ["Frischbetonrohdichte (kg/m³)"],
    pitfalls: ["Lufteinschlüsse beim Verdichten", "Ungenaue Volumenbestimmung des Behälters"],
    normHint: "Orientierung an DIN EN 12350-6.",
  },
  {
    id: "beton-konsistenzklasse",
    title: "Konsistenzklasse",
    category: "Frischbeton",
    shortDescription: "Einordnung der Frischbetonkonsistenz anhand von Ausbreit- oder Setzmaß.",
    location: "Labor & Baustelle",
    status: "Verfügbar",
    tags: ["Labor", "Frischzustand"],
    favorite: false,
    learned: false,
    purpose: "Klassifizierung der Verarbeitbarkeit für die Betonbestellung und -abnahme.",
    equipment: ["Ergebnisse aus Ausbreit- oder Setzmaßprüfung"],
    preparation: ["Ausbreit- oder Setzmaßprüfung durchführen"],
    steps: ["Messwert dem passenden Klassenraster zuordnen", "Konsistenzklasse dokumentieren"],
    inputs: ["Ausbreitmaß oder Setzmaß"],
    outputs: ["Konsistenzklasse (z. B. F3, S2)"],
    pitfalls: ["Falsches Prüfverfahren für die Zielkonsistenz gewählt", "Grenzwerte falsch zugeordnet"],
    normHint: "Orientierung an DIN EN 206.",
  },
  {
    id: "beton-temperatur",
    title: "Temperatur",
    category: "Frischbeton",
    shortDescription: "Frischbetontemperatur zur Kontrolle der Verarbeitungs- und Nachbehandlungsbedingungen.",
    location: "Baustelle",
    status: "Verfügbar",
    tags: ["Baustelle", "Frischzustand"],
    favorite: false,
    learned: false,
    purpose: "Sicherstellen, dass die Betontemperatur im zulässigen Bereich für die Erhärtung liegt.",
    equipment: ["Einstich-Thermometer"],
    preparation: ["Thermometer auf Funktion prüfen"],
    steps: ["Fühler mittig in den Frischbeton einstechen", "Temperatur nach Stabilisierung ablesen"],
    inputs: ["Umgebungstemperatur (°C)"],
    outputs: ["Frischbetontemperatur (°C)"],
    pitfalls: ["Messung zu nah an der Oberfläche", "Fühler nicht tief genug eingestochen"],
    normHint: "Orientierung an DIN 1045-3.",
  },
  {
    id: "beton-wasserzementwert",
    title: "Wasserzementwert",
    category: "Frischbeton",
    shortDescription: "Rechnerische Ermittlung des w/z-Werts aus der Mischungszusammensetzung.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Kontrolle des w/z-Werts als zentraler Kennwert für Festigkeit und Dauerhaftigkeit.",
    equipment: ["Mischungsprotokoll", "Waage"],
    preparation: ["Wasser- und Zementmasse der Mischung dokumentieren"],
    steps: ["Wassermasse durch Zementmasse teilen", "Ergebnis mit Grenzwert der Expositionsklasse vergleichen"],
    inputs: ["Wassermasse (kg)", "Zementmasse (kg)"],
    outputs: ["w/z-Wert (–)"],
    pitfalls: ["Zugabewasser aus Zusatzmitteln nicht berücksichtigt", "Eigenfeuchte der Gesteinskörnung vergessen"],
    normHint: "Orientierung an DIN EN 206.",
  },
  {
    id: "beton-druckfestigkeit",
    title: "Druckfestigkeit",
    category: "Festbeton",
    shortDescription: "Bruchlast von Probekörpern zur Ermittlung der Betondruckfestigkeit.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Festzustand", "Auswertung"],
    favorite: true,
    learned: true,
    purpose: "Nachweis der Druckfestigkeitsklasse am Würfel- oder Zylinderprobekörper.",
    equipment: ["Druckprüfmaschine", "Messschieber"],
    preparation: ["Probekörper vermessen und wiegen", "Lastflächen auf Ebenheit prüfen"],
    steps: ["Probekörper zentrieren", "Last gleichmäßig bis zum Bruch steigern", "Bruchlast ablesen"],
    inputs: ["Bruchlast F (N)", "Querschnittsfläche A (mm²)"],
    outputs: ["Druckfestigkeit (N/mm²)"],
    pitfalls: ["Außermittige Lasteinleitung", "Zu schnelle Laststeigerung", "Beschädigte Lastflächen"],
    normHint: "Orientierung an DIN EN 12390-3.",
  },
  {
    id: "beton-biegezugfestigkeit",
    title: "Biegezugfestigkeit",
    category: "Festbeton",
    shortDescription: "Biegezugfestigkeit an Balkenprobekörpern über Drei- oder Vierpunktbiegung.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Festzustand", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Ermittlung der Biegezugfestigkeit für Straßen- und Industriebetone.",
    equipment: ["Biegeprüfmaschine", "Messschieber"],
    preparation: ["Balkenprobekörper vermessen", "Auflager und Lasteinleitung ausrichten"],
    steps: ["Probekörper mittig auflegen", "Last bis zum Bruch steigern", "Bruchlast und Stützweite notieren"],
    inputs: ["Bruchlast F (N)", "Stützweite l (mm)", "Breite b (mm)", "Höhe h (mm)"],
    outputs: ["Biegezugfestigkeit (N/mm²)"],
    pitfalls: ["Ungleiche Auflagerabstände", "Exzentrische Lasteinleitung"],
    normHint: "Orientierung an DIN EN 12390-5.",
  },
  {
    id: "beton-spaltzugfestigkeit",
    title: "Spaltzugfestigkeit",
    category: "Festbeton",
    shortDescription: "Zugfestigkeit indirekt über Spaltzugversuch am zylindrischen Probekörper.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Festzustand", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Abschätzung der Betonzugfestigkeit ohne direkten Zugversuch.",
    equipment: ["Druckprüfmaschine mit Spaltvorrichtung", "Lastverteilungsstreifen"],
    preparation: ["Zylinder liegend zentrieren", "Lastverteilungsstreifen auflegen"],
    steps: ["Last gleichmäßig bis zum Spaltbruch steigern", "Bruchlast ablesen"],
    inputs: ["Bruchlast F (N)", "Zylinderlänge l (mm)", "Durchmesser d (mm)"],
    outputs: ["Spaltzugfestigkeit (N/mm²)"],
    pitfalls: ["Lastverteilungsstreifen falsch positioniert", "Zylinder nicht exakt liegend zentriert"],
    normHint: "Orientierung an DIN EN 12390-6.",
  },
  {
    id: "beton-festbetonrohdichte",
    title: "Festbetonrohdichte",
    category: "Festbeton",
    shortDescription: "Rohdichte des ausgehärteten Probekörpers aus Masse und Volumen.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Festzustand"],
    favorite: false,
    learned: false,
    purpose: "Qualitätskontrolle des erhärteten Betongefüges.",
    equipment: ["Waage", "Messschieber"],
    preparation: ["Probekörper trocknen bzw. wässern je nach Vorgabe", "Abmessungen bestimmen"],
    steps: ["Masse des Probekörpers wiegen", "Volumen aus Abmessungen berechnen", "Rohdichte berechnen"],
    inputs: ["Masse m (kg)", "Volumen V (m³)"],
    outputs: ["Festbetonrohdichte (kg/m³)"],
    pitfalls: ["Feuchtezustand nicht dokumentiert", "Ungenaue Volumenberechnung bei unebenen Flächen"],
    normHint: "Orientierung an DIN EN 12390-7.",
  },
  {
    id: "beton-wasseraufnahme",
    title: "Wasseraufnahme",
    category: "Festbeton",
    shortDescription: "Kapillare Wasseraufnahme des Festbetons als Dauerhaftigkeitskennwert.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Festzustand", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Beurteilung der Gefügedichtigkeit über die Wasseraufnahme.",
    equipment: ["Wasserbad", "Waage", "Trockenschrank"],
    preparation: ["Probekörper bis Massekonstanz trocknen", "Ausgangsmasse bestimmen"],
    steps: ["Probekörper definiert wässern", "Masse nach Wasserlagerung erneut bestimmen", "Massezunahme berechnen"],
    inputs: ["Trockenmasse (g)", "Masse nach Wässerung (g)"],
    outputs: ["Wasseraufnahme (%)"],
    pitfalls: ["Trocknung nicht bis Massekonstanz", "Probekörperoberfläche vor Wägung nicht abgetupft"],
    normHint: "Orientierung an DIN EN 13369 / betriebliche Prüfanweisung.",
  },
  {
    id: "beton-probekoerperabmessungen",
    title: "Probekörperabmessungen",
    category: "Festbeton",
    shortDescription: "Maßkontrolle von Würfel-, Zylinder- oder Balkenprobekörpern vor der Prüfung.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Sicherstellen normgerechter Abmessungen als Grundlage für Flächen- und Volumenberechnung.",
    equipment: ["Messschieber", "Stahllineal"],
    preparation: ["Probekörper reinigen und auf Beschädigungen prüfen"],
    steps: ["Kantenlängen bzw. Durchmesser an mehreren Stellen messen", "Mittelwerte bilden"],
    inputs: ["Einzelmesswerte (mm)"],
    outputs: ["Mittlere Abmessungen (mm)", "Querschnittsfläche (mm²)"],
    pitfalls: ["Nur eine Messstelle statt Mittelwertbildung", "Abgeplatzte Kanten mitgemessen"],
    normHint: "Orientierung an DIN EN 12390-1.",
  },
  {
    id: "beton-pruefalter",
    title: "Prüfalter",
    category: "Festbeton",
    shortDescription: "Dokumentation des Probenalters zum Prüfzeitpunkt (z. B. 7 oder 28 Tage).",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Sicherstellen vergleichbarer Prüfergebnisse durch definiertes Prüfalter.",
    equipment: ["Herstell- und Prüfprotokoll"],
    preparation: ["Herstelldatum im Probenprotokoll dokumentieren"],
    steps: ["Prüfdatum erfassen", "Differenz zum Herstelldatum in Tagen berechnen"],
    inputs: ["Herstelldatum", "Prüfdatum"],
    outputs: ["Prüfalter (Tage)"],
    pitfalls: ["Herstelldatum nicht dokumentiert", "Abweichung vom vorgesehenen Prüftermin nicht vermerkt"],
    normHint: "Orientierung an DIN EN 12390-2.",
  },
  {
    id: "beton-betondeckung",
    title: "Betondeckung",
    category: "Festbeton",
    shortDescription: "Kontrolle des Abstands zwischen Bewehrung und Bauteiloberfläche.",
    location: "Baustelle",
    status: "In Vorbereitung",
    tags: ["Baustelle", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Sicherstellen des erforderlichen Korrosions- und Brandschutzes der Bewehrung.",
    equipment: ["Betondeckungsmesser", "Referenzstäbe"],
    preparation: ["Messgerät kalibrieren", "Messbereich am Bauteil festlegen"],
    steps: ["Bewehrungslage lokalisieren", "Deckungsmaß an mehreren Punkten messen", "Werte mit Sollwert vergleichen"],
    inputs: ["Sollwert cnom (mm)", "Messwerte (mm)"],
    outputs: ["Ist-Betondeckung (mm)", "Abweichung (mm)"],
    pitfalls: ["Verwechslung von Bewehrungslagen", "Metallische Störeinflüsse am Messgerät"],
    normHint: "Orientierung an DIN EN 1992-1-1 / DIN EN 206.",
  },
  {
    id: "beton-expositionsklassen",
    title: "Expositionsklassen",
    category: "Festbeton",
    shortDescription: "Zuordnung der Umgebungsbedingungen eines Bauteils zu Expositionsklassen.",
    location: "Labor & Baustelle",
    status: "Verfügbar",
    tags: ["Vorbereitung", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Grundlage für Anforderungen an Betonzusammensetzung, w/z-Wert und Betondeckung.",
    equipment: ["Bauwerksunterlagen", "Klassifikationstabelle nach DIN EN 206"],
    preparation: ["Umgebungsbedingungen des Bauteils erfassen (z. B. Feuchte, Chloride, Frost)"],
    steps: ["Zutreffende Expositionsklassen bestimmen", "Anforderungen an Beton ableiten"],
    inputs: ["Umgebungsbedingungen"],
    outputs: ["Expositionsklassen (z. B. XC1, XF3)"],
    pitfalls: ["Mehrfachbeanspruchung nicht vollständig erfasst", "Falsche Einstufung bei Übergangsbereichen"],
    normHint: "Orientierung an DIN EN 206.",
  },
];

const betonCalculators: CalculatorDefinition[] = [
  {
    id: "calc-beton-wz-wert",
    name: "w/z-Wert",
    description: "Wasserzementwert aus Wasser- und Zementmasse berechnen.",
    inputs: [
      { key: "wasser", label: "Wassermasse", unit: "kg" },
      { key: "zement", label: "Zementmasse", unit: "kg" },
    ],
    resultLabel: "w/z-Wert",
    resultUnit: "–",
    plausibilityHint: "Üblich zwischen 0,35 und 0,75.",
    compute: (v) => {
      const zement = parseNumber(v.zement);
      if (!zement) return null;
      return parseNumber(v.wasser) / zement;
    },
  },
  {
    id: "calc-beton-dichte",
    name: "Dichte",
    description: "Dichte aus Masse und Volumen einer Probe berechnen.",
    inputs: [
      { key: "masse", label: "Masse", unit: "kg" },
      { key: "volumen", label: "Volumen", unit: "m³" },
    ],
    resultLabel: "Dichte",
    resultUnit: "kg/m³",
    plausibilityHint: "Beton typischerweise 2.200–2.500 kg/m³.",
    compute: (v) => {
      const volumen = parseNumber(v.volumen);
      if (!volumen) return null;
      return parseNumber(v.masse) / volumen;
    },
  },
  {
    id: "calc-beton-volumen",
    name: "Volumen Würfel",
    description: "Volumen eines würfelförmigen Probekörpers berechnen.",
    inputs: [{ key: "kante", label: "Kantenlänge", unit: "m" }],
    resultLabel: "Volumen",
    resultUnit: "m³",
    plausibilityHint: "Gilt für würfelförmige Probekörper.",
    compute: (v) => {
      const kante = parseNumber(v.kante);
      return Number.isNaN(kante) ? null : kante ** 3;
    },
  },
  {
    id: "calc-beton-druckfestigkeit",
    name: "Druckfestigkeit",
    description: "Druckfestigkeit aus Bruchlast und Querschnittsfläche berechnen.",
    inputs: [
      { key: "bruchlast", label: "Bruchlast", unit: "N" },
      { key: "flaeche", label: "Querschnittsfläche", unit: "mm²" },
    ],
    resultLabel: "Druckfestigkeit",
    resultUnit: "N/mm²",
    compute: (v) => {
      const flaeche = parseNumber(v.flaeche);
      if (!flaeche) return null;
      return parseNumber(v.bruchlast) / flaeche;
    },
  },
  {
    id: "calc-beton-biegezugfestigkeit",
    name: "Biegezugfestigkeit",
    description: "Biegezugfestigkeit nach dem Dreipunkt-Biegeversuch berechnen.",
    inputs: [
      { key: "bruchlast", label: "Bruchlast F", unit: "N" },
      { key: "stuetzweite", label: "Stützweite l", unit: "mm" },
      { key: "breite", label: "Breite b", unit: "mm" },
      { key: "hoehe", label: "Höhe h", unit: "mm" },
    ],
    resultLabel: "Biegezugfestigkeit",
    resultUnit: "N/mm²",
    plausibilityHint: "Berechnung nach dem Dreipunkt-Biegeversuch.",
    compute: (v) => {
      const b = parseNumber(v.breite);
      const h = parseNumber(v.hoehe);
      if (!b || !h) return null;
      return (3 * parseNumber(v.bruchlast) * parseNumber(v.stuetzweite)) / (2 * b * h ** 2);
    },
  },
  {
    id: "calc-beton-mittelwert",
    name: "Mittelwert",
    description: "Mittelwert aus bis zu drei Einzelwerten berechnen.",
    inputs: [
      { key: "wert1", label: "Wert 1" },
      { key: "wert2", label: "Wert 2" },
      { key: "wert3", label: "Wert 3" },
    ],
    resultLabel: "Mittelwert",
    resultUnit: "–",
    compute: (v) => average([v.wert1, v.wert2, v.wert3]),
  },
  {
    id: "calc-beton-pruefalter",
    name: "Prüfalter",
    description: "Prüfalter in Tagen zwischen Herstell- und Prüfdatum berechnen.",
    inputs: [
      { key: "herstelldatum", label: "Herstelldatum", type: "date" },
      { key: "pruefdatum", label: "Prüfdatum", type: "date" },
    ],
    resultLabel: "Prüfalter",
    resultUnit: "Tage",
    plausibilityHint: "Übliche Prüfalter sind 7 oder 28 Tage.",
    compute: (v) => {
      const start = new Date(v.herstelldatum).getTime();
      const end = new Date(v.pruefdatum).getTime();
      if (Number.isNaN(start) || Number.isNaN(end)) return null;
      return Math.round((end - start) / 86_400_000);
    },
  },
];

const betonFormulas: Formula[] = [
  {
    id: "beton-formel-druckfestigkeit",
    name: "Druckfestigkeit",
    formula: "f = F / A",
    unit: "N/mm²",
    variables: [
      { symbol: "F", description: "Bruchlast in N" },
      { symbol: "A", description: "Querschnittsfläche in mm²" },
    ],
    example: "F = 450.000 N, A = 22.500 mm² → f = 20 N/mm²",
    category: "Beton",
  },
  {
    id: "beton-formel-dichte",
    name: "Dichte",
    formula: "ρ = m / V",
    unit: "kg/m³",
    variables: [
      { symbol: "m", description: "Masse in kg" },
      { symbol: "V", description: "Volumen in m³" },
    ],
    example: "m = 2,4 kg, V = 0,001 m³ → ρ = 2.400 kg/m³",
    category: "Beton",
  },
  {
    id: "beton-formel-wz-wert",
    name: "Wasserzementwert",
    formula: "w/z = mWasser / mZement",
    unit: "–",
    variables: [
      { symbol: "mWasser", description: "Wassermasse in kg" },
      { symbol: "mZement", description: "Zementmasse in kg" },
    ],
    example: "mWasser = 180 kg, mZement = 360 kg → w/z = 0,50",
    category: "Beton",
  },
  {
    id: "beton-formel-volumen",
    name: "Volumen Würfel",
    formula: "V = a³",
    unit: "m³",
    variables: [{ symbol: "a", description: "Kantenlänge in m" }],
    example: "a = 0,15 m → V = 0,003375 m³",
    category: "Beton",
  },
  {
    id: "beton-formel-mittelwert",
    name: "Mittelwert",
    formula: "x̄ = (x1 + x2 + … + xn) / n",
    unit: "–",
    variables: [
      { symbol: "xi", description: "Einzelmesswert" },
      { symbol: "n", description: "Anzahl der Messwerte" },
    ],
    example: "x1 = 32,4; x2 = 33,1; x3 = 32,8 → x̄ = 32,77",
    category: "Beton",
  },
];

const betonNorms: NormReference[] = [
  {
    id: "beton-norm-12350",
    code: "DIN EN 12350-Reihe",
    title: "Prüfung von Frischbeton",
    category: "Beton",
    summary: "Regelt Frischbetonprüfungen wie Ausbreitmaß, Setzmaß, Luftgehalt und Rohdichte.",
  },
  {
    id: "beton-norm-12390",
    code: "DIN EN 12390-Reihe",
    title: "Prüfung von Festbeton",
    category: "Beton",
    summary: "Regelt Herstellung, Lagerung und Prüfung von Festbeton-Probekörpern.",
  },
  {
    id: "beton-norm-206",
    code: "DIN EN 206",
    title: "Beton – Festlegung, Eigenschaften, Herstellung und Konformität",
    category: "Beton",
    summary: "Grundnorm für Beton, u. a. Expositionsklassen, Konsistenz- und Festigkeitsklassen.",
  },
  {
    id: "beton-norm-1045",
    code: "DIN 1045",
    title: "Tragwerke aus Beton, Stahlbeton und Spannbeton",
    category: "Beton",
    summary: "Nationale Anwendungsregeln zu Eurocode 2 für Bemessung und Ausführung von Betonbauwerken.",
  },
];

const betonGlossary: GlossaryTerm[] = [
  { id: "beton-g-ausbreitmass", term: "Ausbreitmaß", definition: "Kennwert für die Konsistenz von Frischbeton, ermittelt am Ausbreittisch." },
  { id: "beton-g-betondeckung", term: "Betondeckung", definition: "Abstand zwischen Bewehrung und Bauteiloberfläche zum Korrosionsschutz." },
  { id: "beton-g-erhaertung", term: "Erhärtung", definition: "Festigkeitsentwicklung des Betons durch die Hydratation des Zements." },
  { id: "beton-g-expositionsklasse", term: "Expositionsklasse", definition: "Einstufung der Umweltbedingungen eines Bauteils nach DIN EN 206." },
  { id: "beton-g-gesteinskoernung", term: "Gesteinskörnung", definition: "Mineralisches Korngemisch (Sand, Kies, Splitt) als Ausgangsstoff für Beton." },
  { id: "beton-g-konsistenz", term: "Konsistenz", definition: "Verarbeitbarkeit von Frischbeton, beschrieben über Klassen wie F1 bis F6." },
  { id: "beton-g-luftgehalt", term: "Luftgehalt", definition: "Anteil eingeschlossener Luftporen im Frischbeton in Vol.-%." },
  { id: "beton-g-nachbehandlung", term: "Nachbehandlung", definition: "Schutzmaßnahmen nach dem Betonieren gegen zu schnelles Austrocknen." },
  { id: "beton-g-pruefalter", term: "Prüfalter", definition: "Alter des Probekörpers zum Prüfzeitpunkt, meist 7 oder 28 Tage." },
  { id: "beton-g-rohdichte", term: "Rohdichte", definition: "Verhältnis von Masse zu Gesamtvolumen eines Stoffes einschließlich Poren." },
  { id: "beton-g-wz-wert", term: "w/z-Wert", definition: "Verhältnis von Wassermasse zu Zementmasse im Frischbeton." },
  { id: "beton-g-zusatzmittel", term: "Zusatzmittel", definition: "Stoff, der Beton- oder Mörteleigenschaften gezielt beeinflusst (z. B. Fließmittel)." },
];

// =============================================================
// Asphalt
// =============================================================

const asphaltProcedures: FieldAreaProcedure[] = [
  {
    id: "asphalt-marshall",
    title: "Marshall-Prüfung",
    category: "Mischgut",
    shortDescription: "Stabilität und Fließwert von Asphaltprobekörpern nach dem Marshall-Verfahren.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: true,
    learned: true,
    purpose: "Beurteilung der Tragfähigkeit und Verformungsstabilität von Asphaltmischgut.",
    equipment: ["Marshall-Presse", "Wasserbad", "Marshall-Verdichter"],
    preparation: ["Probekörper herstellen und verdichten", "Probekörper im Wasserbad temperieren"],
    steps: ["Probekörper in die Prüfvorrichtung einsetzen", "Last bis zum Bruch steigern", "Stabilität und Fließwert ablesen"],
    inputs: ["Bruchlast (N)", "Fließwert (mm)"],
    outputs: ["Marshall-Stabilität (kN)", "Fließwert (mm)"],
    pitfalls: ["Prüftemperatur nicht eingehalten", "Zeit zwischen Wasserbad und Prüfung zu lang"],
    normHint: "Orientierung an DIN EN 12697-34.",
  },
  {
    id: "asphalt-raumdichte",
    title: "Raumdichte",
    category: "Mischgut",
    shortDescription: "Rohdichte des verdichteten Asphaltprobekörpers inklusive Hohlräumen.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: true,
    purpose: "Grundlage für Hohlraumgehalt und Verdichtungsgrad.",
    equipment: ["Waage mit Unterwasserwägung", "Probekörper"],
    preparation: ["Probekörper an Luft und unter Wasser wiegen"],
    steps: ["Trockenmasse bestimmen", "Masse unter Wasser bestimmen", "Raumdichte berechnen"],
    inputs: ["Masse trocken (g)", "Masse unter Wasser (g)"],
    outputs: ["Raumdichte (kg/m³)"],
    pitfalls: ["Luftblasen an der Probe bei Unterwasserwägung", "Probekörper nicht wassergesättigt an der Oberfläche"],
    normHint: "Orientierung an DIN EN 12697-6.",
  },
  {
    id: "asphalt-rohdichte",
    title: "Rohdichte",
    category: "Mischgut",
    shortDescription: "Maximale Rohdichte des bindemittelfreien bzw. entgasten Mischguts.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Referenzdichte zur Berechnung des Hohlraumgehalts.",
    equipment: ["Vakuumgefäß", "Waage"],
    preparation: ["Mischgutprobe auflockern und entlüften"],
    steps: ["Probe im Vakuumverfahren entgasen", "Dichte volumetrisch bestimmen"],
    inputs: ["Masse (g)", "Volumen (cm³)"],
    outputs: ["Maximale Rohdichte ρmax (kg/m³)"],
    pitfalls: ["Unvollständige Entlüftung", "Temperaturabweichung während der Messung"],
    normHint: "Orientierung an DIN EN 12697-5.",
  },
  {
    id: "asphalt-hohlraumgehalt",
    title: "Hohlraumgehalt",
    category: "Verdichtung",
    shortDescription: "Anteil der Luftporen im verdichteten Asphalt in Vol.-%.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: true,
    learned: false,
    purpose: "Zentraler Kennwert für Dauerhaftigkeit und Verformungsbeständigkeit.",
    equipment: ["Ergebnisse aus Raumdichte- und Rohdichteprüfung"],
    preparation: ["Raumdichte und maximale Rohdichte ermitteln"],
    steps: ["Hohlraumgehalt aus beiden Dichten berechnen", "Ergebnis mit Zielwert vergleichen"],
    inputs: ["Raumdichte ρb (kg/m³)", "Maximale Rohdichte ρmax (kg/m³)"],
    outputs: ["Hohlraumgehalt (%)"],
    pitfalls: ["Fehlerfortpflanzung aus ungenauen Dichtewerten", "Falsche Referenzdichte verwendet"],
    normHint: "Orientierung an DIN EN 12697-8.",
  },
  {
    id: "asphalt-verdichtungsgrad",
    title: "Verdichtungsgrad",
    category: "Verdichtung",
    shortDescription: "Vergleich der Einbaudichte mit der Marshall-Referenzdichte.",
    location: "Baustelle",
    status: "Verfügbar",
    tags: ["Baustelle", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Nachweis einer ausreichenden Verdichtung der eingebauten Asphaltschicht.",
    equipment: ["Bohrkernbohrgerät", "Waage mit Unterwasserwägung"],
    preparation: ["Bohrkern aus der eingebauten Schicht entnehmen"],
    steps: ["Raumdichte des Bohrkerns bestimmen", "Verdichtungsgrad zur Referenzdichte berechnen"],
    inputs: ["Raumdichte Bohrkern (kg/m³)", "Marshall-Referenzdichte (kg/m³)"],
    outputs: ["Verdichtungsgrad (%)"],
    pitfalls: ["Ungeeignete Bohrkernstelle gewählt", "Referenzdichte veraltet"],
    normHint: "Orientierung an TP Asphalt-StB.",
  },
  {
    id: "asphalt-sieblinie",
    title: "Sieblinie",
    category: "Mischgut",
    shortDescription: "Korngrößenverteilung der Gesteinskörnung im Asphaltmischgut.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Kontrolle der Kornabstufung gegen die Sollsieblinie.",
    equipment: ["Siebmaschine", "Siebsatz", "Waage"],
    preparation: ["Bindemittel extrahieren", "Gesteinskörnung trocknen"],
    steps: ["Probe auf Siebsatz aufgeben", "Siebmaschine definierte Zeit betreiben", "Rückstände je Sieb wiegen"],
    inputs: ["Rückstandsmassen je Sieb (g)", "Gesamtmasse (g)"],
    outputs: ["Siebdurchgang je Siebweite (%)"],
    pitfalls: ["Siebe nicht vollständig gereinigt", "Zu kurze Siebzeit"],
    normHint: "Orientierung an DIN EN 12697-2.",
  },
  {
    id: "asphalt-bindemittelgehalt",
    title: "Bindemittelgehalt",
    category: "Bindemittel",
    shortDescription: "Anteil des Bitumens im Asphaltmischgut über Extraktion bestimmen.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Kontrolle des Bindemittelgehalts gegen die Erstprüfung bzw. Rezeptur.",
    equipment: ["Extraktionsgerät", "Lösungsmittel", "Waage"],
    preparation: ["Mischgutprobe einwiegen"],
    steps: ["Bindemittel extrahieren", "Rückstand trocknen und wiegen", "Bindemittelgehalt berechnen"],
    inputs: ["Masse Bindemittel (g)", "Gesamtmasse (g)"],
    outputs: ["Bindemittelgehalt (%)"],
    pitfalls: ["Unvollständige Extraktion", "Feinanteil im Lösungsmittel verloren"],
    normHint: "Orientierung an DIN EN 12697-1.",
  },
  {
    id: "asphalt-erweichungspunkt",
    title: "Erweichungspunkt Ring und Kugel",
    category: "Bindemittel",
    shortDescription: "Temperatur, bei der Bitumen unter Prüfbedingungen erweicht.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Kennwert für die Temperaturempfindlichkeit des Bindemittels.",
    equipment: ["Ring-und-Kugel-Apparatur", "Wasser- oder Glycerinbad"],
    preparation: ["Bitumenprobe in Prüfringe einbetten", "Kugeln mittig auflegen"],
    steps: ["Bad mit definierter Aufheizrate erwärmen", "Temperatur beim Kugeldurchbruch ablesen"],
    inputs: ["Ablesetemperatur beider Ringe (°C)"],
    outputs: ["Erweichungspunkt (°C)"],
    pitfalls: ["Ungleichmäßige Aufheizrate", "Luftblasen in der Bitumenprobe"],
    normHint: "Orientierung an DIN EN 1427.",
  },
  {
    id: "asphalt-penetration",
    title: "Penetration",
    category: "Bindemittel",
    shortDescription: "Eindringtiefe einer Normnadel in Bitumen bei definierter Temperatur.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Kennwert für die Konsistenz und Sorteneinteilung von Bitumen.",
    equipment: ["Penetrometer", "Normnadel", "Temperierbad"],
    preparation: ["Bitumenprobe auf Prüftemperatur temperieren"],
    steps: ["Nadel an der Oberfläche ansetzen", "Nadel definierte Zeit einsinken lassen", "Eindringtiefe ablesen"],
    inputs: ["Einsinktiefe (0,1 mm)"],
    outputs: ["Penetration (1/10 mm)"],
    pitfalls: ["Prüftemperatur nicht exakt eingehalten", "Nadel nicht senkrecht positioniert"],
    normHint: "Orientierung an DIN EN 1426.",
  },
  {
    id: "asphalt-bohrkernpruefung",
    title: "Bohrkernprüfung",
    category: "Bohrkern",
    shortDescription: "Entnahme und Prüfung von Bohrkernen aus eingebauten Asphaltschichten.",
    location: "Labor & Baustelle",
    status: "Verfügbar",
    tags: ["Baustelle", "Labor"],
    favorite: false,
    learned: false,
    purpose: "Kontrolle von Schichtaufbau, Dichte und Verdichtungsgrad im Einbauzustand.",
    equipment: ["Kernbohrgerät", "Messschieber", "Waage"],
    preparation: ["Bohrstelle festlegen und markieren"],
    steps: ["Bohrkern entnehmen", "Schichten und Abmessungen dokumentieren", "Bohrloch fachgerecht verschließen"],
    inputs: ["Bohrkerndurchmesser (mm)", "Schichtdicken (mm)"],
    outputs: ["Schichtaufbau", "Raumdichte je Schicht"],
    pitfalls: ["Bohrkern beim Ziehen beschädigt", "Bohrstelle ungünstig gewählt (z. B. Fuge)"],
    normHint: "Orientierung an TP Asphalt-StB.",
  },
  {
    id: "asphalt-schichtdicke",
    title: "Schichtdicke",
    category: "Bohrkern",
    shortDescription: "Messung der Einbaudicke einzelner Asphaltschichten am Bohrkern.",
    location: "Baustelle",
    status: "Verfügbar",
    tags: ["Baustelle", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Nachweis der vertraglich vereinbarten Schichtdicken.",
    equipment: ["Messschieber", "Bohrkern"],
    preparation: ["Schichtgrenzen am Bohrkern markieren"],
    steps: ["Dicke jeder Schicht an mehreren Punkten messen", "Mittelwerte je Schicht bilden"],
    inputs: ["Einzelmesswerte je Schicht (mm)"],
    outputs: ["Mittlere Schichtdicke (mm)"],
    pitfalls: ["Schräg angesetzter Bohrkern verfälscht Messung", "Schichtgrenzen schwer erkennbar"],
    normHint: "Orientierung an TP Asphalt-StB.",
  },
  {
    id: "asphalt-texturtiefe",
    title: "Texturtiefe",
    category: "Oberfläche",
    shortDescription: "Oberflächentextur der Fahrbahn über das Sandflächenverfahren bestimmen.",
    location: "Baustelle",
    status: "Verfügbar",
    tags: ["Baustelle", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Beurteilung der Griffigkeit und Rauheit der fertigen Asphaltoberfläche.",
    equipment: ["Ausgleichssand (definiertes Volumen)", "Verteilscheibe", "Messschieber"],
    preparation: ["Prüffläche reinigen und trocknen"],
    steps: ["Sand kreisförmig verteilen", "Durchmesser der Sandfläche messen", "Texturtiefe berechnen"],
    inputs: ["Sandvolumen (cm³)", "Durchmesser der Fläche (mm)"],
    outputs: ["Mittlere Texturtiefe (mm)"],
    pitfalls: ["Feuchte Fahrbahnoberfläche", "Ungleichmäßiges Verteilen des Sands"],
    normHint: "Orientierung an DIN EN 13036-1.",
  },
  {
    id: "asphalt-wasserempfindlichkeit",
    title: "Wasserempfindlichkeit",
    category: "Mischgut",
    shortDescription: "Einfluss von Wasser auf die Haftfestigkeit zwischen Bitumen und Gesteinskörnung.",
    location: "Labor",
    status: "In Vorbereitung",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Beurteilung des Risikos von Ablösungen (Stripping) im Asphalt.",
    equipment: ["Wasserbad", "Marshall-Presse"],
    preparation: ["Probekörper in trockene und nasse Referenzgruppe teilen"],
    steps: ["Eine Gruppe wasserlagern, andere trocken lagern", "Stabilität beider Gruppen prüfen", "Verhältnis der Ergebnisse bilden"],
    inputs: ["Stabilität trocken (kN)", "Stabilität nass (kN)"],
    outputs: ["Verhältnis nass/trocken (%)"],
    pitfalls: ["Ungleiche Lagerungsbedingungen der Gruppen", "Zu geringe Probenanzahl je Gruppe"],
    normHint: "Orientierung an DIN EN 12697-12.",
  },
  {
    id: "asphalt-spurbildung",
    title: "Spurbildung",
    category: "Oberfläche",
    shortDescription: "Qualitativer UI-Hinweis auf das Verformungsverhalten unter Radlast (Spurbildungstest).",
    location: "Labor",
    status: "In Vorbereitung",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Orientierende Einschätzung der Verformungsbeständigkeit – vollständige Prüfung folgt in einem späteren Ausbauschritt.",
    equipment: ["Gleisbildungsgerät (Wheel-Tracking)"],
    preparation: ["Probeplatte herstellen und temperieren"],
    steps: ["Prüfrad definiert über die Platte führen", "Spurtiefe über die Lastwechsel protokollieren"],
    inputs: ["Lastwechselzahl"],
    outputs: ["Spurtiefe (mm) – als UI-Hinweis"],
    pitfalls: ["Prüftemperatur weicht vom Sollwert ab", "Ergebnis ohne Normbewertung nicht verbindlich"],
    normHint: "Orientierung an DIN EN 12697-22 – hier nur als UI-Hinweis hinterlegt.",
  },
];

const asphaltCalculators: CalculatorDefinition[] = [
  {
    id: "calc-asphalt-verdichtungsgrad",
    name: "Verdichtungsgrad",
    description: "Verdichtungsgrad aus Raumdichte und Marshall-Referenzdichte berechnen.",
    inputs: [
      { key: "raumdichte", label: "Raumdichte", unit: "kg/m³" },
      { key: "referenzdichte", label: "Marshall-Referenzdichte", unit: "kg/m³" },
    ],
    resultLabel: "Verdichtungsgrad",
    resultUnit: "%",
    plausibilityHint: "Zielwerte liegen üblicherweise bei 97–100 %.",
    compute: (v) => {
      const ref = parseNumber(v.referenzdichte);
      if (!ref) return null;
      return (parseNumber(v.raumdichte) / ref) * 100;
    },
  },
  {
    id: "calc-asphalt-hohlraumgehalt",
    name: "Hohlraumgehalt",
    description: "Hohlraumgehalt aus maximaler Rohdichte und Raumdichte berechnen.",
    inputs: [
      { key: "rohdichteMax", label: "Maximale Rohdichte ρmax", unit: "kg/m³" },
      { key: "raumdichte", label: "Raumdichte ρb", unit: "kg/m³" },
    ],
    resultLabel: "Hohlraumgehalt",
    resultUnit: "%",
    compute: (v) => {
      const max = parseNumber(v.rohdichteMax);
      if (!max) return null;
      return ((max - parseNumber(v.raumdichte)) / max) * 100;
    },
  },
  {
    id: "calc-asphalt-raumdichte",
    name: "Raumdichte",
    description: "Raumdichte aus Masse und Volumen einer Probe berechnen.",
    inputs: [
      { key: "masse", label: "Masse", unit: "g" },
      { key: "volumen", label: "Volumen", unit: "cm³" },
    ],
    resultLabel: "Raumdichte",
    resultUnit: "kg/m³",
    compute: (v) => {
      const volumen = parseNumber(v.volumen);
      if (!volumen) return null;
      return (parseNumber(v.masse) / volumen) * 1000;
    },
  },
  {
    id: "calc-asphalt-bindemittelgehalt",
    name: "Bindemittelgehalt",
    description: "Bindemittelgehalt aus Bindemittel- und Gesamtmasse berechnen.",
    inputs: [
      { key: "masseBindemittel", label: "Masse Bindemittel", unit: "g" },
      { key: "masseGesamt", label: "Gesamtmasse", unit: "g" },
    ],
    resultLabel: "Bindemittelgehalt",
    resultUnit: "%",
    compute: (v) => {
      const gesamt = parseNumber(v.masseGesamt);
      if (!gesamt) return null;
      return (parseNumber(v.masseBindemittel) / gesamt) * 100;
    },
  },
  {
    id: "calc-asphalt-siebrueckstand",
    name: "Siebrückstand",
    description: "Prozentualen Siebrückstand aus Rückstands- und Gesamtmasse berechnen.",
    inputs: [
      { key: "masseRueckstand", label: "Masse Rückstand", unit: "g" },
      { key: "masseGesamt", label: "Gesamtmasse", unit: "g" },
    ],
    resultLabel: "Siebrückstand",
    resultUnit: "%",
    compute: (v) => {
      const gesamt = parseNumber(v.masseGesamt);
      if (!gesamt) return null;
      return (parseNumber(v.masseRueckstand) / gesamt) * 100;
    },
  },
  {
    id: "calc-asphalt-siebdurchgang",
    name: "Siebdurchgang",
    description: "Prozentualen Siebdurchgang aus Durchgangs- und Gesamtmasse berechnen.",
    inputs: [
      { key: "masseDurchgang", label: "Masse Durchgang", unit: "g" },
      { key: "masseGesamt", label: "Gesamtmasse", unit: "g" },
    ],
    resultLabel: "Siebdurchgang",
    resultUnit: "%",
    compute: (v) => {
      const gesamt = parseNumber(v.masseGesamt);
      if (!gesamt) return null;
      return (parseNumber(v.masseDurchgang) / gesamt) * 100;
    },
  },
  {
    id: "calc-asphalt-mittelwert",
    name: "Mittelwert",
    description: "Mittelwert aus bis zu drei Einzelwerten berechnen.",
    inputs: [
      { key: "wert1", label: "Wert 1" },
      { key: "wert2", label: "Wert 2" },
      { key: "wert3", label: "Wert 3" },
    ],
    resultLabel: "Mittelwert",
    resultUnit: "–",
    compute: (v) => average([v.wert1, v.wert2, v.wert3]),
  },
];

const asphaltFormulas: Formula[] = [
  {
    id: "asphalt-formel-verdichtungsgrad",
    name: "Verdichtungsgrad",
    formula: "k = ρ / ρm × 100",
    unit: "%",
    variables: [
      { symbol: "ρ", description: "Raumdichte in kg/m³" },
      { symbol: "ρm", description: "Marshall-Referenzdichte in kg/m³" },
    ],
    example: "ρ = 2.380 kg/m³, ρm = 2.420 kg/m³ → k ≈ 98,3 %",
    category: "Asphalt",
  },
  {
    id: "asphalt-formel-hohlraumgehalt",
    name: "Hohlraumgehalt",
    formula: "Vm = (ρmax − ρb) / ρmax × 100",
    unit: "%",
    variables: [
      { symbol: "ρmax", description: "Maximale Rohdichte in kg/m³" },
      { symbol: "ρb", description: "Raumdichte in kg/m³" },
    ],
    example: "ρmax = 2.550 kg/m³, ρb = 2.400 kg/m³ → Vm ≈ 5,9 %",
    category: "Asphalt",
  },
  {
    id: "asphalt-formel-rueckstand",
    name: "Rückstand %",
    formula: "R = mR / mG × 100",
    unit: "%",
    variables: [
      { symbol: "mR", description: "Rückstandsmasse in g" },
      { symbol: "mG", description: "Gesamtmasse in g" },
    ],
    example: "mR = 320 g, mG = 800 g → R = 40 %",
    category: "Asphalt",
  },
  {
    id: "asphalt-formel-durchgang",
    name: "Durchgang %",
    formula: "D = mD / mG × 100",
    unit: "%",
    variables: [
      { symbol: "mD", description: "Durchgangsmasse in g" },
      { symbol: "mG", description: "Gesamtmasse in g" },
    ],
    example: "mD = 480 g, mG = 800 g → D = 60 %",
    category: "Asphalt",
  },
  {
    id: "asphalt-formel-dichte",
    name: "Dichte",
    formula: "ρ = m / V",
    unit: "kg/m³",
    variables: [
      { symbol: "m", description: "Masse in g" },
      { symbol: "V", description: "Volumen in cm³" },
    ],
    example: "m = 238 g, V = 100 cm³ → ρ = 2.380 kg/m³",
    category: "Asphalt",
  },
];

const asphaltNorms: NormReference[] = [
  {
    id: "asphalt-norm-12697",
    code: "DIN EN 12697-Reihe",
    title: "Prüfverfahren für Asphalt",
    category: "Asphalt",
    summary: "Regelt Asphaltprüfungen wie Marshall-Verfahren, Hohlraumgehalt und Sieblinie.",
  },
  {
    id: "asphalt-norm-tp",
    code: "TP Asphalt-StB",
    title: "Technische Prüfvorschriften für Asphalt im Straßenbau",
    category: "Asphalt",
    summary: "Konkretisiert Prüfverfahren und Vorgehen für Asphalt im Straßenbau.",
  },
  {
    id: "asphalt-norm-tl",
    code: "TL Asphalt-StB",
    title: "Technische Lieferbedingungen für Asphaltmischgut",
    category: "Asphalt",
    summary: "Regelt Anforderungen an Asphaltmischgut für den Straßenbau.",
  },
];

const asphaltGlossary: GlossaryTerm[] = [
  { id: "asphalt-g-bindemittel", term: "Bindemittel", definition: "Bitumen als verbindender Bestandteil des Asphaltmischguts." },
  { id: "asphalt-g-bohrkern", term: "Bohrkern", definition: "Zylindrische Probe aus einer eingebauten Asphaltschicht zur Qualitätskontrolle." },
  { id: "asphalt-g-erweichungspunkt", term: "Erweichungspunkt", definition: "Temperatur, bei der Bitumen unter Prüfbedingungen erweicht." },
  { id: "asphalt-g-gesteinskoernung", term: "Gesteinskörnung", definition: "Mineralisches Korngemisch als Ausgangsstoff für Asphaltmischgut." },
  { id: "asphalt-g-hohlraumgehalt", term: "Hohlraumgehalt", definition: "Anteil der Luftporen im verdichteten Asphalt in Vol.-%." },
  { id: "asphalt-g-marshall-stabilitaet", term: "Marshall-Stabilität", definition: "Maximale Prüfkraft beim Marshall-Versuch, Kennwert für die Tragfähigkeit." },
  { id: "asphalt-g-penetration", term: "Penetration", definition: "Eindringtiefe einer Normnadel in Bitumen, Kennwert für dessen Konsistenz." },
  { id: "asphalt-g-schichtdicke", term: "Schichtdicke", definition: "Dicke einer eingebauten Asphaltschicht, gemessen am Bohrkern." },
  { id: "asphalt-g-sieblinie", term: "Sieblinie", definition: "Grafische Darstellung der Korngrößenverteilung eines Gesteinskörnungsgemischs." },
  { id: "asphalt-g-spurbildung", term: "Spurbildung", definition: "Bleibende Verformung der Fahrbahnoberfläche unter Radlast." },
  { id: "asphalt-g-texturtiefe", term: "Texturtiefe", definition: "Maß für die Rauheit der Fahrbahnoberfläche, beeinflusst die Griffigkeit." },
  { id: "asphalt-g-verdichtungsgrad", term: "Verdichtungsgrad", definition: "Verhältnis der erreichten Raumdichte zur Marshall-Referenzdichte in %." },
];

// =============================================================
// Geotechnik
// =============================================================

const geotechnikProcedures: FieldAreaProcedure[] = [
  {
    id: "geo-wassergehalt",
    title: "Wassergehalt",
    category: "Kennwerte",
    shortDescription: "Verhältnis von Wasser- zu Trockenmasse einer Bodenprobe bestimmen.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Vorbereitung"],
    favorite: true,
    learned: true,
    purpose: "Grundlegender bodenmechanischer Kennwert für nahezu alle weiteren Berechnungen.",
    equipment: ["Trockenschrank", "Waage", "Probebehälter"],
    preparation: ["Feuchte Probe unmittelbar nach Entnahme wiegen"],
    steps: ["Probe bei 105 °C bis Massekonstanz trocknen", "Trockenmasse wiegen", "Wassergehalt berechnen"],
    inputs: ["Masse feucht (g)", "Masse trocken (g)"],
    outputs: ["Wassergehalt w (%)"],
    pitfalls: ["Probe vor Wägung ausgetrocknet", "Trocknungstemperatur zu hoch bei organischen Böden"],
    normHint: "Orientierung an DIN EN ISO 17892-1.",
  },
  {
    id: "geo-korndichte",
    title: "Korndichte",
    category: "Kennwerte",
    shortDescription: "Dichte der festen Bodenteilchen ohne Poren (Reindichte).",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Kennwert zur Berechnung von Porenanteil und Sättigungsgrad.",
    equipment: ["Pyknometer", "Waage", "Vakuumpumpe"],
    preparation: ["Bodenprobe trocknen und zerkleinern"],
    steps: ["Probe in Pyknometer einwiegen", "Entlüften und mit Wasser auffüllen", "Korndichte berechnen"],
    inputs: ["Masse Probe (g)", "Masse Pyknometer voll Wasser (g)", "Masse Pyknometer mit Probe und Wasser (g)"],
    outputs: ["Korndichte ρs (g/cm³)"],
    pitfalls: ["Unvollständige Entlüftung", "Temperaturunterschiede während der Messung"],
    normHint: "Orientierung an DIN EN ISO 17892-3.",
  },
  {
    id: "geo-rohdichte",
    title: "Rohdichte",
    category: "Kennwerte",
    shortDescription: "Dichte der ungestörten Bodenprobe einschließlich Poren.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Grundlage für Trockendichte- und Verdichtungsberechnungen.",
    equipment: ["Ausstechzylinder", "Waage", "Messschieber"],
    preparation: ["Ungestörte Probe mit Ausstechzylinder entnehmen"],
    steps: ["Masse der Probe im Zylinder bestimmen", "Zylindervolumen berechnen", "Rohdichte berechnen"],
    inputs: ["Masse (g)", "Volumen (cm³)"],
    outputs: ["Rohdichte ρ (g/cm³)"],
    pitfalls: ["Probe beim Ausstechen gestört", "Randlücken am Zylinder nicht erkannt"],
    normHint: "Orientierung an DIN EN ISO 17892-2.",
  },
  {
    id: "geo-proctorversuch",
    title: "Proctorversuch",
    category: "Verdichtung",
    shortDescription: "Zusammenhang zwischen Wassergehalt und erreichbarer Trockendichte ermitteln.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: true,
    learned: true,
    purpose: "Bestimmung von Proctordichte und optimalem Wassergehalt als Verdichtungsreferenz.",
    equipment: ["Proctortopf", "Fallgewicht (Proctorhammer)", "Waage"],
    preparation: ["Bodenproben mit unterschiedlichem Wassergehalt vorbereiten"],
    steps: ["Boden in Lagen einfüllen und mit definierter Schlagzahl verdichten", "Feuchtdichte je Probe bestimmen", "Trockendichte berechnen und Proctorkurve auftragen"],
    inputs: ["Masse je Probe (g)", "Wassergehalt je Probe (%)"],
    outputs: ["Proctordichte ρd,max (kg/m³)", "Optimaler Wassergehalt wopt (%)"],
    pitfalls: ["Ungleichmäßige Verdichtung der Lagen", "Zu wenige Stützpunkte für die Proctorkurve"],
    normHint: "Orientierung an DIN EN 13286-2.",
  },
  {
    id: "geo-verdichtungsgrad",
    title: "Verdichtungsgrad",
    category: "Verdichtung",
    shortDescription: "Vergleich der erreichten Trockendichte mit der Proctordichte.",
    location: "Baustelle",
    status: "Verfügbar",
    tags: ["Baustelle", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Nachweis einer ausreichenden Verdichtung im Erdbau.",
    equipment: ["Ausstechzylinder oder Isotopensonde", "Waage"],
    preparation: ["Trockendichte vor Ort bestimmen"],
    steps: ["Erreichte Trockendichte ermitteln", "Verhältnis zur Proctordichte berechnen"],
    inputs: ["Trockendichte ρd (kg/m³)", "Proctordichte ρpr (kg/m³)"],
    outputs: ["Verdichtungsgrad Dpr (%)"],
    pitfalls: ["Falsche Referenz-Proctordichte verwendet", "Messstelle nicht repräsentativ"],
    normHint: "Orientierung an DIN 18126 / DIN EN 13286-2.",
  },
  {
    id: "geo-siebanalyse",
    title: "Siebanalyse",
    category: "Kornverteilung",
    shortDescription: "Korngrößenverteilung des Bodens im Grobkornbereich über Siebung.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Grundlage für die Bodenklassifikation und Kennwerte wie Cu und Cc.",
    equipment: ["Siebmaschine", "Siebsatz", "Waage"],
    preparation: ["Probe trocknen und ggf. waschen"],
    steps: ["Probe auf Siebsatz aufgeben", "Siebmaschine definierte Zeit betreiben", "Rückstände je Sieb wiegen"],
    inputs: ["Rückstandsmassen je Sieb (g)", "Gesamtmasse (g)"],
    outputs: ["Sieblinie / Siebdurchgang je Korngröße (%)"],
    pitfalls: ["Verklebte Feinanteile ohne Waschen gesiebt", "Siebe nicht vollständig gereinigt"],
    normHint: "Orientierung an DIN EN ISO 17892-4.",
  },
  {
    id: "geo-schlaemmanalyse",
    title: "Schlämmanalyse",
    category: "Kornverteilung",
    shortDescription: "Korngrößenverteilung im Feinkornbereich über die Sedimentationsgeschwindigkeit.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Ergänzung der Siebanalyse für Schluff- und Tonanteile.",
    equipment: ["Aräometer", "Sedimentationszylinder", "Dispergiermittel"],
    preparation: ["Feinkornprobe mit Dispergiermittel aufbereiten"],
    steps: ["Suspension aufschütteln und Zylinder aufstellen", "Dichte zu definierten Zeitpunkten mit Aräometer messen", "Korngrößenanteile berechnen"],
    inputs: ["Aräometerwerte zu definierten Zeiten"],
    outputs: ["Kornanteile Schluff/Ton (%)"],
    pitfalls: ["Unvollständige Dispergierung führt zu Klümpchenbildung", "Temperaturschwankungen während der Sedimentation"],
    normHint: "Orientierung an DIN EN ISO 17892-4.",
  },
  {
    id: "geo-atterberg",
    title: "Atterberg-Grenzen",
    category: "Konsistenz",
    shortDescription: "Zustandsgrenzen bindiger Böden zwischen flüssig, plastisch und fest bestimmen.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: true,
    learned: false,
    purpose: "Grundlage für Plastizitätszahl und Bodenklassifikation.",
    equipment: ["Fließgrenzengerät (Casagrande)", "Ausrollplatte"],
    preparation: ["Bodenprobe aufbereiten und homogenisieren"],
    steps: ["Fließgrenze über Casagrande-Gerät bestimmen", "Ausrollgrenze über Ausrollversuch bestimmen"],
    inputs: ["Wassergehalt bei Fließgrenze (%)", "Wassergehalt bei Ausrollgrenze (%)"],
    outputs: ["Fließgrenze wL (%)", "Ausrollgrenze wP (%)"],
    pitfalls: ["Falsche Schlagzahl beim Casagrande-Versuch", "Boden beim Ausrollen zu trocken"],
    normHint: "Orientierung an DIN EN ISO 17892-12.",
  },
  {
    id: "geo-fliessgrenze",
    title: "Fließgrenze",
    category: "Konsistenz",
    shortDescription: "Wassergehalt am Übergang von plastischem zu flüssigem Zustand.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Teilergebnis der Atterberg-Grenzen, obere Grenze des plastischen Bereichs.",
    equipment: ["Casagrande-Gerät", "Furchenzieher"],
    preparation: ["Probe in die Schale einbringen und glätten"],
    steps: ["Furche einziehen", "Schale bis zum Schließen der Furche schlagen", "Wassergehalt bei ca. 25 Schlägen bestimmen"],
    inputs: ["Schlagzahl", "Wassergehalt je Messung (%)"],
    outputs: ["Fließgrenze wL (%)"],
    pitfalls: ["Furche nicht normgerecht gezogen", "Falltisch nicht korrekt justiert"],
    normHint: "Orientierung an DIN EN ISO 17892-12.",
  },
  {
    id: "geo-ausrollgrenze",
    title: "Ausrollgrenze",
    category: "Konsistenz",
    shortDescription: "Wassergehalt am Übergang von halbfestem zu plastischem Zustand.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Teilergebnis der Atterberg-Grenzen, untere Grenze des plastischen Bereichs.",
    equipment: ["Ausrollplatte (unglasiert)"],
    preparation: ["Probe auf Ausrollfähigkeit vorbereiten"],
    steps: ["Boden zu 3 mm Röllchen ausrollen", "Wassergehalt beim ersten Brechen bestimmen"],
    inputs: ["Wassergehalt bei Bruch (%)"],
    outputs: ["Ausrollgrenze wP (%)"],
    pitfalls: ["Röllchen zu schnell ausgerollt", "Boden bereits zu trocken bei Versuchsbeginn"],
    normHint: "Orientierung an DIN EN ISO 17892-12.",
  },
  {
    id: "geo-plastizitaetszahl",
    title: "Plastizitätszahl",
    category: "Konsistenz",
    shortDescription: "Rechnerische Spannweite des plastischen Bereichs aus Fließ- und Ausrollgrenze.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Kennwert zur Einordnung der Plastizität im Plastizitätsdiagramm.",
    equipment: ["Ergebnisse aus Fließ- und Ausrollgrenze"],
    preparation: ["Fließ- und Ausrollgrenze ermitteln"],
    steps: ["Ausrollgrenze von Fließgrenze subtrahieren", "Ergebnis im Plastizitätsdiagramm einordnen"],
    inputs: ["Fließgrenze wL (%)", "Ausrollgrenze wP (%)"],
    outputs: ["Plastizitätszahl IP (%)"],
    pitfalls: ["Ungenaue Einzelwerte übernommen", "Verwechslung von wL und wP"],
    normHint: "Orientierung an DIN EN ISO 14688-2.",
  },
  {
    id: "geo-bodenklassifikation",
    title: "Bodenklassifikation",
    category: "Klassifikation",
    shortDescription: "Einteilung des Bodens in Bodengruppen nach Korngröße und Plastizität.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Auswertung"],
    favorite: false,
    learned: false,
    purpose: "Grundlage für bautechnische Einstufung und Verwendbarkeit als Baustoff.",
    equipment: ["Ergebnisse aus Sieb-/Schlämmanalyse und Atterberg-Grenzen"],
    preparation: ["Kornverteilung und Plastizitätskennwerte zusammenstellen"],
    steps: ["Bodengruppe anhand Kornverteilung und Plastizitätsdiagramm bestimmen", "Klassifikation dokumentieren"],
    inputs: ["Kornverteilung", "Plastizitätszahl IP (%)"],
    outputs: ["Bodengruppe (z. B. GW, TL, SU)"],
    pitfalls: ["Grenzfälle zwischen zwei Bodengruppen falsch entschieden", "Organische Anteile nicht berücksichtigt"],
    normHint: "Orientierung an DIN 18196.",
  },
  {
    id: "geo-organische-bestandteile",
    title: "Organische Bestandteile",
    category: "Klassifikation",
    shortDescription: "Nachweis und grobe Abschätzung organischer Anteile im Boden.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Beurteilung der Eignung des Bodens für bautechnische Zwecke.",
    equipment: ["Wasserstoffperoxid-Test oder Glühofen", "Waage"],
    preparation: ["Probe trocknen und homogenisieren"],
    steps: ["Vortest auf organische Bestandteile durchführen", "Bei Bedarf Glühverlust ergänzend bestimmen"],
    inputs: ["Probenmasse (g)"],
    outputs: ["Einschätzung organischer Anteil (gering/mittel/hoch)"],
    pitfalls: ["Unzureichende Homogenisierung der Probe", "Vortest ohne Bestätigung durch Glühverlust überbewertet"],
    normHint: "Orientierung an DIN 18128 / DIN 19684.",
  },
  {
    id: "geo-kalkgehalt",
    title: "Kalkgehalt",
    category: "Klassifikation",
    shortDescription: "Karbonatgehalt des Bodens über die gasvolumetrische Methode (Scheibler).",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Kennwert für Bodenverhalten bei Kalkung und bautechnischer Verwendbarkeit.",
    equipment: ["Scheibler-Apparatur", "Salzsäure", "Waage"],
    preparation: ["Probe trocknen und fein aufmahlen"],
    steps: ["Probe mit Salzsäure versetzen", "Entstehendes CO2-Volumen messen", "Kalkgehalt berechnen"],
    inputs: ["Probenmasse (g)", "CO2-Volumen (ml)"],
    outputs: ["Kalkgehalt CaCO3 (%)"],
    pitfalls: ["Undichte Apparatur verfälscht Gasvolumen", "Reaktionszeit zu kurz gewählt"],
    normHint: "Orientierung an DIN 18129.",
  },
  {
    id: "geo-gluehverlust",
    title: "Glühverlust",
    category: "Klassifikation",
    shortDescription: "Massenverlust einer Bodenprobe beim Glühen als Hinweis auf organische Anteile.",
    location: "Labor",
    status: "Verfügbar",
    tags: ["Labor", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Ergänzender Kennwert zur Beurteilung organischer Bestandteile.",
    equipment: ["Muffelofen", "Waage", "Tiegel"],
    preparation: ["Probe bei 105 °C trocknen und wiegen"],
    steps: ["Probe bei definierter Temperatur glühen", "Masse nach dem Glühen bestimmen", "Glühverlust berechnen"],
    inputs: ["Masse vor dem Glühen (g)", "Masse nach dem Glühen (g)"],
    outputs: ["Glühverlust (%)"],
    pitfalls: ["Glühtemperatur nicht eingehalten", "Probe nach dem Glühen nicht im Exsikkator abgekühlt"],
    normHint: "Orientierung an DIN 18128.",
  },
  {
    id: "geo-probenahme",
    title: "Probenahme",
    category: "Feldarbeit",
    shortDescription: "Repräsentative Entnahme von Bodenproben im Feld.",
    location: "Baustelle",
    status: "Verfügbar",
    tags: ["Baustelle", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Grundlage für aussagekräftige Laborergebnisse.",
    equipment: ["Handbohrer oder Rammkernsonde", "Probenbehälter", "Beschriftung"],
    preparation: ["Entnahmestellen nach Untersuchungsprogramm festlegen"],
    steps: ["Probe entnehmen und Störung minimieren", "Probe luftdicht verpacken und beschriften", "Entnahmetiefe und -ort dokumentieren"],
    inputs: ["Entnahmetiefe (m)", "Entnahmeort (Koordinaten)"],
    outputs: ["Beschriftete Bodenprobe mit Protokoll"],
    pitfalls: ["Probe nicht luftdicht verpackt (Wassergehalt verändert sich)", "Entnahmetiefe ungenau dokumentiert"],
    normHint: "Orientierung an DIN EN ISO 22475-1.",
  },
  {
    id: "geo-bodenbeschreibung",
    title: "Bodenbeschreibung",
    category: "Feldarbeit",
    shortDescription: "Visuelle und haptische Ansprache des Bodens im Feld nach einheitlichem Schema.",
    location: "Baustelle",
    status: "In Vorbereitung",
    tags: ["Baustelle", "Vorbereitung"],
    favorite: false,
    learned: false,
    purpose: "Erste orientierende Einschätzung von Bodenart und -zustand vor der Laboranalyse.",
    equipment: ["Bodenbeschreibungsschema", "Klappspaten", "Lupe"],
    preparation: ["Ungestörtes Bodenprofil freilegen"],
    steps: ["Farbe, Konsistenz und Kornverteilung visuell/haptisch ansprechen", "Beschreibung nach einheitlichem Schema dokumentieren"],
    inputs: ["Beobachtungen im Feld"],
    outputs: ["Bodenbeschreibung (Kurzbezeichnung)"],
    pitfalls: ["Subjektive Einschätzung ohne Laborabgleich als endgültig behandelt", "Uneinheitliche Beschreibungssystematik"],
    normHint: "Orientierung an DIN EN ISO 14688-1.",
  },
];

const geotechnikCalculators: CalculatorDefinition[] = [
  {
    id: "calc-geo-wassergehalt",
    name: "Wassergehalt",
    description: "Wassergehalt aus feuchter und trockener Probenmasse berechnen.",
    inputs: [
      { key: "feucht", label: "Masse feucht", unit: "g" },
      { key: "trocken", label: "Masse trocken", unit: "g" },
    ],
    resultLabel: "Wassergehalt",
    resultUnit: "%",
    compute: (v) => {
      const trocken = parseNumber(v.trocken);
      if (!trocken) return null;
      return ((parseNumber(v.feucht) - trocken) / trocken) * 100;
    },
  },
  {
    id: "calc-geo-trockendichte",
    name: "Trockendichte",
    description: "Trockendichte aus Feuchtdichte und Wassergehalt berechnen.",
    inputs: [
      { key: "feuchtdichte", label: "Feuchtdichte", unit: "kg/m³" },
      { key: "wassergehalt", label: "Wassergehalt", unit: "%" },
    ],
    resultLabel: "Trockendichte",
    resultUnit: "kg/m³",
    compute: (v) => {
      const w = parseNumber(v.wassergehalt);
      if (Number.isNaN(w)) return null;
      return parseNumber(v.feuchtdichte) / (1 + w / 100);
    },
  },
  {
    id: "calc-geo-verdichtungsgrad",
    name: "Verdichtungsgrad",
    description: "Verdichtungsgrad aus Trockendichte und Proctordichte berechnen.",
    inputs: [
      { key: "trockendichte", label: "Trockendichte", unit: "kg/m³" },
      { key: "proctordichte", label: "Proctordichte", unit: "kg/m³" },
    ],
    resultLabel: "Verdichtungsgrad",
    resultUnit: "%",
    plausibilityHint: "Im Erdbau meist mindestens 97–100 % gefordert.",
    compute: (v) => {
      const proctor = parseNumber(v.proctordichte);
      if (!proctor) return null;
      return (parseNumber(v.trockendichte) / proctor) * 100;
    },
  },
  {
    id: "calc-geo-plastizitaetszahl",
    name: "Plastizitätszahl",
    description: "Plastizitätszahl aus Fließ- und Ausrollgrenze berechnen.",
    inputs: [
      { key: "fliessgrenze", label: "Fließgrenze wL", unit: "%" },
      { key: "ausrollgrenze", label: "Ausrollgrenze wP", unit: "%" },
    ],
    resultLabel: "Plastizitätszahl",
    resultUnit: "%",
    compute: (v) => parseNumber(v.fliessgrenze) - parseNumber(v.ausrollgrenze),
  },
  {
    id: "calc-geo-ungleichfoermigkeitszahl",
    name: "Ungleichförmigkeitszahl",
    description: "Ungleichförmigkeitszahl aus d60 und d10 der Sieblinie berechnen.",
    inputs: [
      { key: "d60", label: "d60", unit: "mm" },
      { key: "d10", label: "d10", unit: "mm" },
    ],
    resultLabel: "Ungleichförmigkeitszahl U",
    resultUnit: "–",
    compute: (v) => {
      const d10 = parseNumber(v.d10);
      if (!d10) return null;
      return parseNumber(v.d60) / d10;
    },
  },
  {
    id: "calc-geo-kruemmungszahl",
    name: "Krümmungszahl",
    description: "Krümmungszahl aus d10, d30 und d60 der Sieblinie berechnen.",
    inputs: [
      { key: "d10", label: "d10", unit: "mm" },
      { key: "d30", label: "d30", unit: "mm" },
      { key: "d60", label: "d60", unit: "mm" },
    ],
    resultLabel: "Krümmungszahl C",
    resultUnit: "–",
    compute: (v) => {
      const d10 = parseNumber(v.d10);
      const d60 = parseNumber(v.d60);
      if (!d10 || !d60) return null;
      return parseNumber(v.d30) ** 2 / (d10 * d60);
    },
  },
  {
    id: "calc-geo-siebrueckstand",
    name: "Siebrückstand",
    description: "Prozentualen Siebrückstand aus Rückstands- und Gesamtmasse berechnen.",
    inputs: [
      { key: "masseRueckstand", label: "Masse Rückstand", unit: "g" },
      { key: "masseGesamt", label: "Gesamtmasse", unit: "g" },
    ],
    resultLabel: "Siebrückstand",
    resultUnit: "%",
    compute: (v) => {
      const gesamt = parseNumber(v.masseGesamt);
      if (!gesamt) return null;
      return (parseNumber(v.masseRueckstand) / gesamt) * 100;
    },
  },
  {
    id: "calc-geo-siebdurchgang",
    name: "Siebdurchgang",
    description: "Prozentualen Siebdurchgang aus Durchgangs- und Gesamtmasse berechnen.",
    inputs: [
      { key: "masseDurchgang", label: "Masse Durchgang", unit: "g" },
      { key: "masseGesamt", label: "Gesamtmasse", unit: "g" },
    ],
    resultLabel: "Siebdurchgang",
    resultUnit: "%",
    compute: (v) => {
      const gesamt = parseNumber(v.masseGesamt);
      if (!gesamt) return null;
      return (parseNumber(v.masseDurchgang) / gesamt) * 100;
    },
  },
];

const geotechnikFormulas: Formula[] = [
  {
    id: "geo-formel-wassergehalt",
    name: "Wassergehalt",
    formula: "w = (m_feucht − m_trocken) / m_trocken × 100",
    unit: "%",
    variables: [
      { symbol: "m_feucht", description: "Masse der feuchten Probe in g" },
      { symbol: "m_trocken", description: "Masse der ofengetrockneten Probe in g" },
    ],
    example: "m_feucht = 180 g, m_trocken = 150 g → w = 20 %",
    category: "Geotechnik",
  },
  {
    id: "geo-formel-plastizitaetszahl",
    name: "Plastizitätszahl",
    formula: "I_P = w_L − w_P",
    unit: "%",
    variables: [
      { symbol: "w_L", description: "Fließgrenze in %" },
      { symbol: "w_P", description: "Ausrollgrenze in %" },
    ],
    example: "w_L = 42 %, w_P = 24 % → I_P = 18 %",
    category: "Geotechnik",
  },
  {
    id: "geo-formel-verdichtungsgrad",
    name: "Verdichtungsgrad",
    formula: "D_Pr = ρ_d / ρ_d,max × 100",
    unit: "%",
    variables: [
      { symbol: "ρ_d", description: "Erreichte Trockendichte in kg/m³" },
      { symbol: "ρ_d,max", description: "Proctordichte in kg/m³" },
    ],
    example: "ρ_d = 1.900 kg/m³, ρ_d,max = 2.000 kg/m³ → D_Pr = 95 %",
    category: "Geotechnik",
  },
  {
    id: "geo-formel-ungleichfoermigkeitszahl",
    name: "Ungleichförmigkeitszahl",
    formula: "U = d60 / d10",
    unit: "–",
    variables: [
      { symbol: "d60", description: "Korndurchmesser bei 60 % Siebdurchgang in mm" },
      { symbol: "d10", description: "Korndurchmesser bei 10 % Siebdurchgang in mm" },
    ],
    example: "d60 = 2,4 mm, d10 = 0,3 mm → U = 8",
    category: "Geotechnik",
  },
  {
    id: "geo-formel-kruemmungszahl",
    name: "Krümmungszahl",
    formula: "C = d30² / (d10 × d60)",
    unit: "–",
    variables: [
      { symbol: "d30", description: "Korndurchmesser bei 30 % Siebdurchgang in mm" },
      { symbol: "d10", description: "Korndurchmesser bei 10 % Siebdurchgang in mm" },
      { symbol: "d60", description: "Korndurchmesser bei 60 % Siebdurchgang in mm" },
    ],
    example: "d30 = 0,9 mm, d10 = 0,3 mm, d60 = 2,4 mm → C = 1,13",
    category: "Geotechnik",
  },
];

const geotechnikNorms: NormReference[] = [
  {
    id: "geo-norm-14688-1",
    code: "DIN EN ISO 14688-1",
    title: "Geotechnische Erkundung und Untersuchung – Benennung, Beschreibung und Klassifizierung von Boden – Teil 1: Benennung und Beschreibung",
    category: "Geotechnik",
    summary: "Grundlage für die einheitliche Benennung und Beschreibung von Böden im Feld.",
  },
  {
    id: "geo-norm-14688-2",
    code: "DIN EN ISO 14688-2",
    title: "Geotechnische Erkundung und Untersuchung – Teil 2: Grundlagen für Bodenklassifizierungen",
    category: "Geotechnik",
    summary: "Grundlagen zur Klassifizierung von Böden nach Korngröße und Plastizität.",
  },
  {
    id: "geo-norm-17892",
    code: "DIN EN ISO 17892-Reihe",
    title: "Geotechnische Erkundung und Untersuchung – Laborversuche an Bodenproben",
    category: "Geotechnik",
    summary: "Regelt bodenmechanische Laborversuche wie Wassergehalt, Dichte und Atterberg-Grenzen.",
  },
  {
    id: "geo-norm-18196",
    code: "DIN 18196",
    title: "Erd- und Grundbau – Bodenklassifikation für bautechnische Zwecke",
    category: "Geotechnik",
    summary: "Systematik zur Einteilung von Böden nach Korngrößenverteilung und Plastizität.",
  },
];

const geotechnikGlossary: GlossaryTerm[] = [
  { id: "geo-g-atterberg", term: "Atterberg-Grenzen", definition: "Zustandsgrenzen bindiger Böden zwischen flüssig, plastisch und fest." },
  { id: "geo-g-ausrollgrenze", term: "Ausrollgrenze", definition: "Wassergehalt am Übergang von halbfestem zu plastischem Zustand." },
  { id: "geo-g-bodenklassifikation", term: "Bodenklassifikation", definition: "Einteilung von Böden nach Korngröße und Plastizität in Bodengruppen." },
  { id: "geo-g-fliessgrenze", term: "Fließgrenze", definition: "Wassergehalt am Übergang von plastischem zu flüssigem Zustand." },
  { id: "geo-g-gluehverlust", term: "Glühverlust", definition: "Massenverlust einer Bodenprobe beim Glühen als Hinweis auf organische Anteile." },
  { id: "geo-g-konsistenzzahl", term: "Konsistenzzahl", definition: "Kennwert zur Einordnung des Bodenzustands zwischen Ausroll- und Fließgrenze." },
  { id: "geo-g-plastizitaetszahl", term: "Plastizitätszahl", definition: "Spannweite des plastischen Bereichs, berechnet aus Fließ- und Ausrollgrenze." },
  { id: "geo-g-proctordichte", term: "Proctordichte", definition: "Maximal erreichbare Trockendichte eines Bodens beim Proctor-Versuch." },
  { id: "geo-g-sieblinie", term: "Sieblinie", definition: "Grafische Darstellung der Korngrößenverteilung eines Bodens." },
  { id: "geo-g-verdichtungsgrad", term: "Verdichtungsgrad", definition: "Verhältnis der erreichten Trockendichte zur Proctordichte in %." },
  { id: "geo-g-wassergehalt", term: "Wassergehalt", definition: "Verhältnis von Wasser- zu Trockenmasse einer Bodenprobe in %." },
  { id: "geo-g-ungleichfoermigkeitszahl", term: "Ungleichförmigkeitszahl", definition: "Kennwert Cu = d60/d10 zur Beurteilung der Kornabstufung eines Bodens." },
].sort((a, b) => a.term.localeCompare(b.term, "de"));

// =============================================================
// Field area configs
// =============================================================

export const fieldAreas: Record<FieldAreaId, FieldAreaConfig> = {
  beton: {
    id: "beton",
    title: "Beton",
    subtitle: "Prüfverfahren, Berechnungen und Normhinweise für Frisch- und Festbeton.",
    icon: Building2,
    applicableFilterTags: ["Labor", "Baustelle", "Frischzustand", "Festzustand", "Vorbereitung", "Auswertung"],
    procedures: betonProcedures,
    calculators: betonCalculators,
    formulas: betonFormulas,
    norms: betonNorms,
    glossary: betonGlossary,
  },
  asphalt: {
    id: "asphalt",
    title: "Asphalt",
    subtitle: "Prüfverfahren, Kennwerte und Berechnungen für Asphalt, Bitumen und Bohrkerne.",
    icon: Layers,
    applicableFilterTags: ["Labor", "Baustelle", "Vorbereitung", "Auswertung"],
    procedures: asphaltProcedures,
    calculators: asphaltCalculators,
    formulas: asphaltFormulas,
    norms: asphaltNorms,
    glossary: asphaltGlossary,
  },
  geotechnik: {
    id: "geotechnik",
    title: "Geotechnik",
    subtitle: "Bodenmechanische Prüfverfahren, Klassifikation und Berechnungen für Baugrund und Bodenproben.",
    icon: Mountain,
    applicableFilterTags: ["Labor", "Baustelle", "Vorbereitung", "Auswertung"],
    procedures: geotechnikProcedures,
    calculators: geotechnikCalculators,
    formulas: geotechnikFormulas,
    norms: geotechnikNorms,
    glossary: geotechnikGlossary,
  },
};
