import type { Invitation } from "@/types/invitation";

// Mock-Daten für die Einladungsverwaltung (Tab "Einladungen" in /company).
// Eigenständiger Datensatz, keine Firebase-Anbindung.

export const invitations: Invitation[] = [
  {
    id: "inv-eva",
    name: "Eva König",
    initials: "EK",
    email: "eva@musterlabor.de",
    role: "Gast",
    location: "Baustellenbüro Nord",
    status: "Offen",
    invitedBy: "Max Mustermann",
    createdAt: "01.03.2026",
    expiresAt: "15.03.2026",
    link: "https://app.pruefcheckpro.de/invite/eva-koenig-8f2a",
    history: [{ message: "Einladung als Gast erstellt.", timestamp: "01.03.2026" }],
  },
  {
    id: "inv-sophie",
    name: "Sophie Bauer",
    initials: "SB",
    email: "sophie@musterlabor.de",
    role: "Prüfer",
    location: "Labor Stuttgart",
    status: "Offen",
    invitedBy: "Anna Neumann",
    createdAt: "28.02.2026",
    expiresAt: "14.03.2026",
    lastReminder: "03.03.2026",
    link: "https://app.pruefcheckpro.de/invite/sophie-bauer-19c4",
    history: [
      { message: "Einladung als Prüfer erstellt.", timestamp: "28.02.2026" },
      { message: "Erinnerung gesendet.", timestamp: "03.03.2026" },
    ],
  },
  {
    id: "inv-jan",
    name: "Jan Weber",
    initials: "JW",
    email: "jan@musterlabor.de",
    role: "Azubi",
    location: "Labor Remseck",
    status: "Angenommen",
    invitedBy: "Tom Müller",
    createdAt: "20.02.2026",
    expiresAt: "06.03.2026",
    link: "https://app.pruefcheckpro.de/invite/jan-weber-77d1",
    history: [
      { message: "Einladung als Azubi erstellt.", timestamp: "20.02.2026" },
      { message: "Einladung angenommen.", timestamp: "22.02.2026" },
    ],
  },
  {
    id: "inv-miriam",
    name: "Miriam Koch",
    initials: "MK",
    email: "miriam@musterlabor.de",
    role: "Laborleiter",
    location: "Labor München",
    status: "Abgelaufen",
    invitedBy: "Max Mustermann",
    createdAt: "10.01.2026",
    expiresAt: "24.01.2026",
    lastReminder: "18.01.2026",
    link: "https://app.pruefcheckpro.de/invite/miriam-koch-4b30",
    history: [
      { message: "Einladung als Laborleiter erstellt.", timestamp: "10.01.2026" },
      { message: "Erinnerung gesendet.", timestamp: "18.01.2026" },
      { message: "Einladung abgelaufen.", timestamp: "24.01.2026" },
    ],
  },
  {
    id: "inv-felix",
    name: "Felix Braun",
    initials: "FB",
    email: "felix@musterlabor.de",
    role: "Prüfer",
    location: "Labor Stuttgart",
    status: "Widerrufen",
    invitedBy: "Anna Neumann",
    createdAt: "15.01.2026",
    expiresAt: "29.01.2026",
    link: "https://app.pruefcheckpro.de/invite/felix-braun-9e21",
    history: [
      { message: "Einladung als Prüfer erstellt.", timestamp: "15.01.2026" },
      { message: "Einladung widerrufen.", timestamp: "17.01.2026" },
    ],
  },
];
