import type { LaborbookEntry } from "@/types/laborbook";

// Mock-Daten für das Laborbuch (/laborbuch). Eigenständiger Datensatz,
// keine Firebase-Anbindung. Proben-/Projekt-/Kunden-/Gerätenamen bewusst
// konsistent mit config/samples.ts und config/devices.ts gehalten.

export const HEUTE = "03.03.2026";
export const DIESE_WOCHE = [
  "02.03.2026",
  "03.03.2026",
  "04.03.2026",
  "05.03.2026",
  "06.03.2026",
  "07.03.2026",
  "08.03.2026",
];

export const laborbookEntries: LaborbookEntry[] = [
  {
    id: "LOG-2026-001",
    datum: "03.03.2026",
    uhrzeit: "09:12",
    typ: "Prüfung",
    fachbereich: "Beton",
    titel: "Druckfestigkeit erfasst – BET-2026-014",
    beschreibung: "Prüfwerte für die 28-Tage-Druckfestigkeit wurden dokumentiert.",
    projekt: "Neubau Wohnanlage Parkblick",
    kunde: "Musterbau GmbH",
    probeId: "BET-2026-014",
    mitarbeiter: "Anna Neumann",
    status: "Aktiv",
    fotos: [{ id: "f-1", title: "Foto Bruchbild.jpg", date: "03.03.2026" }],
    dokumente: [{ id: "d-1", title: "Prüfprotokoll.pdf", date: "03.03.2026" }],
    historie: [{ message: "Eintrag angelegt.", timestamp: "03.03.2026, 09:12 Uhr" }],
  },
  {
    id: "LOG-2026-002",
    datum: "03.03.2026",
    uhrzeit: "08:30",
    typ: "Prüfung",
    fachbereich: "Beton",
    titel: "Betonprobe – Druckfestigkeit dokumentiert",
    beschreibung: "Würfelprüfung C30/37 abgeschlossen und im System vermerkt.",
    projekt: "Neubau Wohnanlage Parkblick",
    kunde: "Musterbau GmbH",
    probeId: "BET-2026-022",
    mitarbeiter: "Anna Neumann",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "03.03.2026, 08:30 Uhr" }],
  },
  {
    id: "LOG-2026-003",
    datum: "02.03.2026",
    uhrzeit: "15:45",
    typ: "Prüfung",
    fachbereich: "Geotechnik",
    titel: "Wassergehalt bestimmt – GEO-2026-033",
    beschreibung: "Wassergehalt der Bodenprobe Lehm nach DIN EN ISO 17892 bestimmt.",
    projekt: "Baugebiet Nord",
    kunde: "Musterbau GmbH",
    probeId: "GEO-2026-033",
    mitarbeiter: "A. Meier",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "02.03.2026, 15:45 Uhr" }],
  },
  {
    id: "LOG-2026-004",
    datum: "02.03.2026",
    uhrzeit: "14:20",
    typ: "Prüfung",
    fachbereich: "Asphalt",
    titel: "Sieblinie dokumentiert – ASP-2026-044",
    beschreibung: "Sieblinie für Asphaltmischgut AC 11 DS erfasst.",
    projekt: "L 342 Fahrbahnerneuerung",
    kunde: "Straßenbau Nord",
    probeId: "ASP-2026-044",
    mitarbeiter: "S. Wolf",
    status: "Aktiv",
    fotos: [{ id: "f-2", title: "Foto Mischgut.jpg", date: "02.03.2026" }],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "02.03.2026, 14:20 Uhr" }],
  },
  {
    id: "LOG-2026-005",
    datum: "01.03.2026",
    uhrzeit: "11:10",
    typ: "Prüfung",
    fachbereich: "Beton",
    titel: "Biegezugfestigkeit – PR-2026-008",
    beschreibung: "Biegezugprüfung am Betonprisma durchgeführt.",
    projekt: "Brückensanierung B17",
    kunde: "Baresel AG",
    probeId: "PR-2026-008",
    mitarbeiter: "T. Keller",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "01.03.2026, 11:10 Uhr" }],
  },
  {
    id: "LOG-2026-006",
    datum: "04.03.2026",
    uhrzeit: "10:05",
    typ: "Gerät",
    titel: "Druckprüfpresse in Betrieb genommen",
    beschreibung: "Gerät nach planmäßiger Wartung wieder in Betrieb genommen.",
    geraet: "Druckprüfpresse (DR-001)",
    mitarbeiter: "Anna Neumann",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "04.03.2026, 10:05 Uhr" }],
  },
  {
    id: "LOG-2026-007",
    datum: "28.02.2026",
    uhrzeit: "09:40",
    typ: "Gerät",
    titel: "Präzisionswaage außer Betrieb gemeldet",
    beschreibung: "Waage zeigt Abweichungen – für Kalibrierung vorgemerkt.",
    geraet: "Präzisionswaage (WA-014)",
    mitarbeiter: "Tom Müller",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "28.02.2026, 09:40 Uhr" }],
  },
  {
    id: "LOG-2026-008",
    datum: "15.09.2025",
    uhrzeit: "13:00",
    typ: "Kalibrierung",
    titel: "Kalibrierung dokumentiert – Druckprüfpresse (DR-001)",
    beschreibung: "Jährliche Kalibrierung durchgeführt, Zertifikat hinterlegt.",
    geraet: "Druckprüfpresse (DR-001)",
    mitarbeiter: "Anna Neumann",
    status: "Aktiv",
    fotos: [],
    dokumente: [{ id: "d-2", title: "Kalibrierschein-DR-001-2025.pdf", date: "15.09.2025" }],
    historie: [{ message: "Eintrag angelegt.", timestamp: "15.09.2025, 13:00 Uhr" }],
  },
  {
    id: "LOG-2026-009",
    datum: "20.02.2025",
    uhrzeit: "10:30",
    typ: "Kalibrierung",
    titel: "Kalibrierung dokumentiert – Präzisionswaage (WA-014)",
    beschreibung: "Kalibrierung im Rahmen des jährlichen Turnus durchgeführt.",
    geraet: "Präzisionswaage (WA-014)",
    mitarbeiter: "Tom Müller",
    status: "Aktiv",
    fotos: [],
    dokumente: [{ id: "d-3", title: "Kalibrierschein-WA-014-2025.pdf", date: "20.02.2025" }],
    historie: [{ message: "Eintrag angelegt.", timestamp: "20.02.2025, 10:30 Uhr" }],
  },
  {
    id: "LOG-2026-010",
    datum: "10.01.2026",
    uhrzeit: "08:15",
    typ: "Wartung",
    titel: "Wartung durchgeführt – Druckprüfpresse (DR-001)",
    beschreibung: "Planmäßige Wartung inkl. Sichtprüfung und Funktionstest.",
    geraet: "Druckprüfpresse (DR-001)",
    mitarbeiter: "Anna Neumann",
    status: "Aktiv",
    fotos: [],
    dokumente: [{ id: "d-4", title: "Wartungsprotokoll.pdf", date: "10.01.2026" }],
    historie: [{ message: "Eintrag angelegt.", timestamp: "10.01.2026, 08:15 Uhr" }],
  },
  {
    id: "LOG-2026-011",
    datum: "05.08.2025",
    uhrzeit: "09:00",
    typ: "Wartung",
    titel: "Wartung durchgeführt – Präzisionswaage (WA-014)",
    beschreibung: "Jährliche Wartung und Justierung durchgeführt.",
    geraet: "Präzisionswaage (WA-014)",
    mitarbeiter: "Tom Müller",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "05.08.2025, 09:00 Uhr" }],
  },
  {
    id: "LOG-2026-012",
    datum: "03.03.2026",
    uhrzeit: "07:50",
    typ: "Notiz",
    titel: "Laborraum 2 gereinigt und Geräte kontrolliert",
    beschreibung: "Routinekontrolle vor Prüfbeginn, keine Auffälligkeiten.",
    mitarbeiter: "S. Wolf",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "03.03.2026, 07:50 Uhr" }],
  },
  {
    id: "LOG-2026-013",
    datum: "26.02.2026",
    uhrzeit: "16:30",
    typ: "Notiz",
    fachbereich: "Geotechnik",
    titel: "Ungewöhnliche Körnung bei Bodenprobe",
    beschreibung: "Bodenprobe zeigt ungewöhnliche Körnung – Rücksprache mit Bauleitung nötig.",
    projekt: "Baugebiet Nord",
    kunde: "Musterbau GmbH",
    probeId: "GEO-2026-021",
    mitarbeiter: "A. Meier",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "26.02.2026, 16:30 Uhr" }],
  },
  {
    id: "LOG-2026-014",
    datum: "20.02.2026",
    uhrzeit: "09:00",
    typ: "Ereignis",
    titel: "Internes Laboraudit durchgeführt",
    beschreibung: "Jährliches internes Audit zur Qualitätssicherung durchgeführt.",
    mitarbeiter: "T. Keller",
    status: "Aktiv",
    fotos: [],
    dokumente: [{ id: "d-5", title: "Auditbericht.pdf", date: "20.02.2026" }],
    historie: [{ message: "Eintrag angelegt.", timestamp: "20.02.2026, 09:00 Uhr" }],
  },
  {
    id: "LOG-2026-015",
    datum: "18.02.2026",
    uhrzeit: "13:15",
    typ: "Ereignis",
    titel: "Neue Mitarbeiterin eingewiesen",
    beschreibung: "Laboreinweisung und Sicherheitsunterweisung durchgeführt.",
    mitarbeiter: "T. Keller",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "18.02.2026, 13:15 Uhr" }],
  },
  {
    id: "LOG-2026-016",
    datum: "25.02.2026",
    uhrzeit: "10:20",
    typ: "Prüfung",
    fachbereich: "Asphalt",
    titel: "Marshall-Prüfung – ASP-2026-011",
    beschreibung: "Marshall-Stabilität und Fließwert am Asphaltbohrkern ermittelt.",
    projekt: "L 342 Fahrbahnerneuerung",
    kunde: "Straßenbau Nord",
    probeId: "ASP-2026-011",
    mitarbeiter: "S. Wolf",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "25.02.2026, 10:20 Uhr" }],
  },
  {
    id: "LOG-2026-017",
    datum: "27.02.2026",
    uhrzeit: "08:45",
    typ: "Prüfung",
    fachbereich: "Geotechnik",
    titel: "Proctor-Versuch – GEO-2026-021",
    beschreibung: "Proctorversuch zur Bestimmung der Verdichtungskennwerte durchgeführt.",
    projekt: "Baugebiet Nord",
    kunde: "Musterbau GmbH",
    probeId: "GEO-2026-021",
    mitarbeiter: "A. Meier",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "27.02.2026, 08:45 Uhr" }],
  },
  {
    id: "LOG-2026-018",
    datum: "05.03.2026",
    uhrzeit: "09:30",
    typ: "Kalibrierung",
    titel: "Kalibrierung dokumentiert – Klimaschrank (KS-002)",
    beschreibung: "Temperatur- und Feuchtekalibrierung durchgeführt.",
    geraet: "Klimaschrank (KS-002)",
    mitarbeiter: "Anna Neumann",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "05.03.2026, 09:30 Uhr" }],
  },
  {
    id: "LOG-2026-019",
    datum: "06.03.2026",
    uhrzeit: "14:00",
    typ: "Wartung",
    titel: "Wartung durchgeführt – Siebmaschine (SI-011)",
    beschreibung: "Reinigung der Siebe und Funktionsprüfung durchgeführt.",
    geraet: "Siebmaschine (SI-011)",
    mitarbeiter: "S. Wolf",
    status: "Aktiv",
    fotos: [],
    dokumente: [],
    historie: [{ message: "Eintrag angelegt.", timestamp: "06.03.2026, 14:00 Uhr" }],
  },
  {
    id: "LOG-2026-020",
    datum: "30.12.2025",
    uhrzeit: "10:00",
    typ: "Prüfung",
    fachbereich: "Beton",
    titel: "Druckfestigkeit dokumentiert – BET-2025-098",
    beschreibung: "Abschließende Druckfestigkeitsprüfung, Projekt seither abgeschlossen.",
    projekt: "Neubau Wohnanlage Parkblick",
    kunde: "Musterbau GmbH",
    probeId: "BET-2025-098",
    mitarbeiter: "T. Keller",
    status: "Archiviert",
    fotos: [],
    dokumente: [{ id: "d-6", title: "Prüfprotokoll.pdf", date: "30.12.2025" }],
    historie: [
      { message: "Eintrag angelegt.", timestamp: "30.12.2025, 10:00 Uhr" },
      { message: "Eintrag archiviert.", timestamp: "15.01.2026, 09:00 Uhr" },
    ],
  },
  {
    id: "LOG-2026-021",
    datum: "28.01.2026",
    uhrzeit: "09:00",
    typ: "Ereignis",
    titel: "Jahresinventur Laborgeräte abgeschlossen",
    beschreibung: "Jährliche Inventur aller Laborgeräte durchgeführt und dokumentiert.",
    mitarbeiter: "T. Keller",
    status: "Archiviert",
    fotos: [],
    dokumente: [],
    historie: [
      { message: "Eintrag angelegt.", timestamp: "28.01.2026, 09:00 Uhr" },
      { message: "Eintrag archiviert.", timestamp: "01.02.2026, 09:00 Uhr" },
    ],
  },
  {
    id: "LOG-2026-022",
    datum: "15.01.2026",
    uhrzeit: "11:00",
    typ: "Notiz",
    titel: "Altbestand Prüfprotokolle digitalisiert",
    beschreibung: "Papierprotokolle aus 2024 eingescannt und archiviert.",
    mitarbeiter: "Anna Neumann",
    status: "Archiviert",
    fotos: [],
    dokumente: [],
    historie: [
      { message: "Eintrag angelegt.", timestamp: "15.01.2026, 11:00 Uhr" },
      { message: "Eintrag archiviert.", timestamp: "20.01.2026, 09:00 Uhr" },
    ],
  },
];
