import type { CompanyLocationDetail } from "@/types/location";

// Mock-Daten für die Standorte-Verwaltung (Tab "Standorte" in /company).
// Eigenständiger Datensatz für diesen Sprint, keine Firebase-Anbindung.

export const companyLocationDetails: CompanyLocationDetail[] = [
  {
    id: "loc-stuttgart",
    name: "Labor Stuttgart",
    type: "Hauptstandort",
    street: "Industriestraße 12",
    postalCode: "70190",
    city: "Stuttgart",
    country: "Deutschland",
    contactPerson: "Max Mustermann",
    phone: "+49 711 1234567",
    email: "stuttgart@musterlabor.de",
    timezone: "Europe/Berlin (UTC+1)",
    employeeCount: 5,
    deviceCount: 18,
    projectCount: 12,
    status: "Aktiv",
    history: [
      { message: "Standort wurde als Hauptstandort festgelegt.", timestamp: "03.01.2024" },
      { message: "Ansprechpartner auf Max Mustermann geändert.", timestamp: "14.06.2025" },
    ],
  },
  {
    id: "loc-remseck",
    name: "Labor Remseck",
    type: "Außenstelle",
    street: "Neckarstraße 8",
    postalCode: "71686",
    city: "Remseck",
    country: "Deutschland",
    contactPerson: "Anna Neumann",
    phone: "+49 7146 987654",
    email: "remseck@musterlabor.de",
    timezone: "Europe/Berlin (UTC+1)",
    employeeCount: 3,
    deviceCount: 9,
    projectCount: 6,
    status: "Aktiv",
    history: [{ message: "Standort wurde angelegt.", timestamp: "22.09.2024" }],
  },
  {
    id: "loc-muenchen",
    name: "Labor München",
    type: "Außenstelle",
    street: "Baierbrunner Str. 15",
    postalCode: "81379",
    city: "München",
    country: "Deutschland",
    contactPerson: "Tom Müller",
    phone: "+49 89 9876543",
    email: "muenchen@musterlabor.de",
    timezone: "Europe/Berlin (UTC+1)",
    employeeCount: 4,
    deviceCount: 12,
    projectCount: 9,
    status: "Aktiv",
    history: [
      { message: "Standort wurde angelegt.", timestamp: "05.03.2024" },
      { message: "2 neue Geräte zugeordnet.", timestamp: "18.02.2026" },
    ],
  },
  {
    id: "loc-baustelle-nord",
    name: "Baustellenbüro Nord",
    type: "Baustellenbüro",
    street: "Baugebiet Nord",
    postalCode: "70439",
    city: "Stuttgart",
    country: "Deutschland",
    contactPerson: "Laura Schneider",
    phone: "+49 711 5551212",
    email: "baustelle-nord@musterlabor.de",
    timezone: "Europe/Berlin (UTC+1)",
    employeeCount: 0,
    deviceCount: 3,
    projectCount: 1,
    status: "Inaktiv",
    history: [
      { message: "Standort wurde angelegt.", timestamp: "11.11.2025" },
      { message: "Standort wurde deaktiviert.", timestamp: "20.02.2026" },
    ],
  },
];
