import type { QuizQuestion } from "@/types/quiz";

// Mock-Fragen für den Quizbereich (/quiz). Eigenständiger Datensatz,
// keine Firebase-Anbindung, rein lokal ausgewertet.

export const quizQuestions: QuizQuestion[] = [
  // Beton
  {
    id: "q-beton-01",
    type: "multiple-choice",
    category: "Beton",
    difficulty: "Leicht",
    question: "Was bewirkt ein niedriger w/z-Wert im Beton?",
    options: [
      "Höhere Festigkeit und Dichtigkeit",
      "Schnelleres Erstarren des Zements",
      "Geringere Materialkosten",
      "Höherer Wasserbedarf beim Mischen",
    ],
    correctIndex: 0,
    explanation:
      "Ein niedriger w/z-Wert führt zu einem dichteren Gefüge und damit zu höherer Festigkeit und Dauerhaftigkeit des Betons.",
  },
  {
    id: "q-beton-02",
    type: "true-false",
    category: "Beton",
    difficulty: "Leicht",
    question: "Ein höherer Luftgehalt im Frischbeton kann den Frost-Tau-Widerstand verbessern.",
    correctAnswer: true,
    explanation:
      "Künstlich eingeführte Luftporen wirken als Ausdehnungsräume für gefrierendes Wasser und erhöhen so den Frost-Tau-Widerstand.",
  },
  {
    id: "q-beton-03",
    type: "numeric",
    category: "Beton",
    difficulty: "Mittel",
    question: "Berechne die Druckfestigkeit fc bei einer Bruchlast F = 360.000 N und einer Querschnittsfläche A = 20.000 mm².",
    correctValue: 18,
    unit: "N/mm²",
    tolerance: 0.5,
    explanation: "fc = F / A = 360.000 N / 20.000 mm² = 18 N/mm².",
  },
  {
    id: "q-beton-04",
    type: "multiple-choice",
    category: "Beton",
    difficulty: "Mittel",
    question: "Mit welchem Gerät wird das Ausbreitmaß von Frischbeton ermittelt?",
    options: ["Ausbreittisch", "Setztrichter (Slump-Test)", "Vebe-Gerät", "Luftgehaltsprüfer"],
    correctIndex: 0,
    explanation:
      "Das Ausbreitmaß wird nach DIN EN 12350-5 am Ausbreittisch durch Anheben eines Setztrichters und Ausbreiten des Betons ermittelt.",
  },
  {
    id: "q-beton-05",
    type: "true-false",
    category: "Beton",
    difficulty: "Mittel",
    question: "Die Betondeckung schützt die Bewehrung vor Korrosion und Feuer.",
    correctAnswer: true,
    explanation:
      "Die Betondeckung ist die wesentliche konstruktive Maßnahme zum Schutz der Bewehrung vor Korrosion und im Brandfall.",
  },
  {
    id: "q-beton-06",
    type: "multiple-choice",
    category: "Beton",
    difficulty: "Schwer",
    question: "Welche Expositionsklasse nach DIN EN 206 beschreibt die Korrosion durch Karbonatisierung?",
    options: ["XC", "XD", "XF", "XA"],
    correctIndex: 0,
    explanation:
      "XC steht für Bewehrungskorrosion, verursacht durch Karbonatisierung. XD steht für Chloride, XF für Frostangriff, XA für chemischen Angriff.",
  },
  {
    id: "q-beton-07",
    type: "matching",
    category: "Beton",
    difficulty: "Mittel",
    question: "Ordne jedes Prüfgerät der Frischbetoneigenschaft zu, die es bestimmt.",
    pairs: [
      { left: "Ausbreittisch", right: "Konsistenz" },
      { left: "Luftgehaltsprüfer", right: "Luftporengehalt" },
      { left: "Waage & Messbehälter", right: "Frischbetonrohdichte" },
    ],
    explanation:
      "Konsistenz wird über den Ausbreittisch, Luftporengehalt über den Luftgehaltsprüfer und Rohdichte über Wiegen des Frischbetons im Messbehälter bestimmt.",
  },
  {
    id: "q-beton-08",
    type: "ordering",
    category: "Beton",
    difficulty: "Schwer",
    question: "Bringe die Arbeitsschritte der Druckfestigkeitsprüfung an Betonwürfeln in die richtige Reihenfolge.",
    steps: [
      "Probekörper vermessen",
      "Probekörper in Prüfmaschine zentrieren",
      "Last gleichmäßig steigern",
      "Bruchlast ablesen",
      "Druckfestigkeit berechnen",
    ],
    explanation:
      "Erst wird der Probekörper vermessen und zentriert, dann die Last gesteigert, die Bruchlast abgelesen und daraus die Druckfestigkeit berechnet.",
  },

  // Asphalt
  {
    id: "q-asphalt-01",
    type: "multiple-choice",
    category: "Asphalt",
    difficulty: "Leicht",
    question: "Mit welchem Verfahren wird die Marshall-Stabilität von Asphalt ermittelt?",
    options: ["Marshall-Verfahren", "Proctor-Verfahren", "CBR-Verfahren", "Vebe-Verfahren"],
    correctIndex: 0,
    explanation: "Das Marshall-Verfahren bestimmt Stabilität und Fließwert an genormt verdichteten Asphaltprobekörpern.",
  },
  {
    id: "q-asphalt-02",
    type: "true-false",
    category: "Asphalt",
    difficulty: "Leicht",
    question: "Ein zu hoher Hohlraumgehalt im Asphalt begünstigt Wassereintritt und Alterung.",
    correctAnswer: true,
    explanation: "Zu hohe Hohlraumgehalte lassen Wasser und Luft eindringen, was Alterung und Frostschäden begünstigt.",
  },
  {
    id: "q-asphalt-03",
    type: "numeric",
    category: "Asphalt",
    difficulty: "Mittel",
    question: "Berechne den Hohlraumgehalt Vm bei ρmax = 2.500 kg/m³ und ρb = 2.350 kg/m³.",
    correctValue: 6,
    unit: "%",
    tolerance: 0.3,
    explanation: "Vm = (ρmax − ρb) / ρmax × 100 = (2.500 − 2.350) / 2.500 × 100 = 6 %.",
  },
  {
    id: "q-asphalt-04",
    type: "multiple-choice",
    category: "Asphalt",
    difficulty: "Mittel",
    question: "Was beschreibt der Erweichungspunkt Ring und Kugel?",
    options: [
      "Die Temperaturempfindlichkeit von Bitumen",
      "Die Kornfestigkeit der Gesteinskörnung",
      "Den Wassergehalt des Mischguts",
      "Den Verdichtungsgrad der Asphaltschicht",
    ],
    correctIndex: 0,
    explanation:
      "Der Erweichungspunkt Ring und Kugel gibt an, bei welcher Temperatur Bitumen unter definierten Bedingungen erweicht.",
  },
  {
    id: "q-asphalt-05",
    type: "multiple-choice",
    category: "Asphalt",
    difficulty: "Schwer",
    question: "Welches Prüfverfahren bestimmt die Korngrößenverteilung von Asphaltmischgut?",
    options: ["Siebanalyse", "Marshall-Versuch", "Ring-und-Kugel-Verfahren", "Proctor-Versuch"],
    correctIndex: 0,
    explanation: "Nach Extraktion des Bindemittels wird die Korngrößenverteilung mittels Siebanalyse bestimmt.",
  },
  {
    id: "q-asphalt-06",
    type: "true-false",
    category: "Asphalt",
    difficulty: "Mittel",
    question: "Die Sieblinie stellt den prozentualen Siebdurchgang über der Siebweite dar.",
    correctAnswer: true,
    explanation: "Die Sieblinie ist die grafische Darstellung des Siebdurchgangs in % über der (meist logarithmischen) Siebweite.",
  },
  {
    id: "q-asphalt-07",
    type: "ordering",
    category: "Asphalt",
    difficulty: "Mittel",
    question: "Bringe die Schritte der Marshall-Prüfung in die richtige Reihenfolge.",
    steps: [
      "Probekörper herstellen und verdichten",
      "Probekörper im Wasserbad temperieren",
      "Probekörper in das Prüfgerät einlegen",
      "Last bis zum Bruch steigern",
      "Stabilität und Fließwert ablesen",
    ],
    explanation:
      "Nach Herstellung und Temperierung wird der Probekörper geprüft, bis zum Bruch belastet und Stabilität sowie Fließwert abgelesen.",
  },

  // Geotechnik
  {
    id: "q-geo-01",
    type: "multiple-choice",
    category: "Geotechnik",
    difficulty: "Leicht",
    question: "Was wird mit dem Proctor-Versuch ermittelt?",
    options: [
      "Optimaler Wassergehalt und Proctordichte eines Bodens",
      "Tragfähigkeit einer Fahrbahn direkt",
      "Kornfestigkeit der Gesteinskörnung",
      "Wasserdurchlässigkeit des Bodens",
    ],
    correctIndex: 0,
    explanation: "Der Proctor-Versuch bestimmt den Zusammenhang zwischen Wassergehalt und erreichbarer Trockendichte eines Bodens.",
  },
  {
    id: "q-geo-02",
    type: "true-false",
    category: "Geotechnik",
    difficulty: "Leicht",
    question: "Die Fließgrenze ist eine der Atterberg-Grenzen.",
    correctAnswer: true,
    explanation: "Zu den Atterberg-Grenzen zählen Fließgrenze, Ausrollgrenze und Schrumpfgrenze.",
  },
  {
    id: "q-geo-03",
    type: "numeric",
    category: "Geotechnik",
    difficulty: "Mittel",
    question: "Berechne den Wassergehalt w bei mfeucht = 180 g und mtrocken = 150 g.",
    correctValue: 20,
    unit: "%",
    tolerance: 0.5,
    explanation: "w = (mfeucht − mtrocken) / mtrocken × 100 = (180 − 150) / 150 × 100 = 20 %.",
  },
  {
    id: "q-geo-04",
    type: "multiple-choice",
    category: "Geotechnik",
    difficulty: "Mittel",
    question: "Wonach richtet sich die Bodenklassifikation nach DIN 18196?",
    options: [
      "Korngrößenverteilung und Plastizitätseigenschaften",
      "Wassergehalt allein",
      "Farbe und Geruch der Probe",
      "Ausschließlich dem Kalkgehalt",
    ],
    correctIndex: 0,
    explanation: "Die Bodengruppen nach DIN 18196 ergeben sich aus Korngrößenverteilung und Plastizität.",
  },
  {
    id: "q-geo-05",
    type: "numeric",
    category: "Geotechnik",
    difficulty: "Schwer",
    question: "Berechne den Verdichtungsgrad Dpr bei ρd = 1.900 kg/m³ und ρpr = 2.000 kg/m³.",
    correctValue: 95,
    unit: "%",
    tolerance: 0.5,
    explanation: "Dpr = ρd / ρpr × 100 = 1.900 / 2.000 × 100 = 95 %.",
  },
  {
    id: "q-geo-06",
    type: "matching",
    category: "Geotechnik",
    difficulty: "Mittel",
    question: "Ordne jeden Bodenversuch seinem Untersuchungsziel zu.",
    pairs: [
      { left: "Proctor-Versuch", right: "Optimaler Wassergehalt / Proctordichte" },
      { left: "Atterberg-Grenzen", right: "Plastizitätseigenschaften" },
      { left: "Sieb- und Schlämmanalyse", right: "Korngrößenverteilung" },
    ],
    explanation:
      "Jeder Versuch liefert einen spezifischen bodenmechanischen Kennwert zur Beurteilung des Baugrunds.",
  },
  {
    id: "q-geo-07",
    type: "true-false",
    category: "Geotechnik",
    difficulty: "Schwer",
    question: "Der Verdichtungsgrad ist das Verhältnis von erreichter Trockendichte zur Proctordichte.",
    correctAnswer: true,
    explanation: "Dpr = ρd / ρpr × 100 beschreibt genau dieses Verhältnis.",
  },

  // Fachrechnen
  {
    id: "q-fach-01",
    type: "numeric",
    category: "Fachrechnen",
    difficulty: "Leicht",
    question: "Berechne die Rohdichte ρ bei m = 3,0 kg und V = 0,00125 m³.",
    correctValue: 2400,
    unit: "kg/m³",
    tolerance: 20,
    explanation: "ρ = m / V = 3,0 / 0,00125 = 2.400 kg/m³.",
  },
  {
    id: "q-fach-02",
    type: "multiple-choice",
    category: "Fachrechnen",
    difficulty: "Leicht",
    question: "Wie berechnet sich das Volumen eines Würfels mit Kantenlänge a?",
    options: ["V = a³", "V = a²", "V = 4a", "V = a² / 2"],
    correctIndex: 0,
    explanation: "Das Volumen eines Würfels ergibt sich aus der Kantenlänge hoch drei: V = a³.",
  },
  {
    id: "q-fach-03",
    type: "numeric",
    category: "Fachrechnen",
    difficulty: "Mittel",
    question: "Berechne die Ungleichförmigkeitszahl Cu bei d60 = 3,6 mm und d10 = 0,4 mm.",
    correctValue: 9,
    tolerance: 0.2,
    explanation: "Cu = d60 / d10 = 3,6 / 0,4 = 9.",
  },
  {
    id: "q-fach-04",
    type: "multiple-choice",
    category: "Fachrechnen",
    difficulty: "Mittel",
    question: "In welcher Einheit wird die Dichte in der Bauprüfung üblicherweise angegeben?",
    options: ["kg/m³", "N/mm²", "kg/mm³", "g/cm"],
    correctIndex: 0,
    explanation: "Dichte wird in der Bauprüfpraxis meist in kg/m³ angegeben.",
  },
  {
    id: "q-fach-05",
    type: "true-false",
    category: "Fachrechnen",
    difficulty: "Mittel",
    question: "Die Rohdichte berücksichtigt auch die im Material enthaltenen Poren.",
    correctAnswer: true,
    explanation: "Im Gegensatz zur Reindichte bezieht die Rohdichte das Gesamtvolumen inklusive Poren mit ein.",
  },
  {
    id: "q-fach-06",
    type: "ordering",
    category: "Fachrechnen",
    difficulty: "Leicht",
    question: "Bringe die Schritte einer Dichteberechnung in die richtige Reihenfolge.",
    steps: [
      "Probe wiegen (Masse bestimmen)",
      "Volumen der Probe ermitteln",
      "Masse durch Volumen teilen",
      "Ergebnis in kg/m³ angeben",
    ],
    explanation: "Dichte ergibt sich aus Masse geteilt durch Volumen, das Ergebnis wird in kg/m³ angegeben.",
  },
  {
    id: "q-fach-07",
    type: "multiple-choice",
    category: "Fachrechnen",
    difficulty: "Schwer",
    question: "Wie verhält sich die Ungleichförmigkeitszahl Cu bei einer sehr gleichförmigen Kornverteilung?",
    options: ["Sie wird klein (nahe 1)", "Sie wird groß (über 15)", "Sie bleibt 0", "Sie wird negativ"],
    correctIndex: 0,
    explanation: "Eine gleichförmige Kornverteilung führt zu einem Cu nahe 1, eine breit gestufte Verteilung zu großen Cu-Werten.",
  },

  // Normen
  {
    id: "q-norm-01",
    type: "multiple-choice",
    category: "Normen",
    difficulty: "Leicht",
    question: "Was regelt die DIN EN 206?",
    options: [
      "Festlegung, Eigenschaften und Herstellung von Beton",
      "Prüfverfahren für Asphalt",
      "Bodenklassifikation für bautechnische Zwecke",
      "Anforderungen an Prüflaboratorien",
    ],
    correctIndex: 0,
    explanation: "DIN EN 206 ist die Grundnorm für Beton – Festlegung, Eigenschaften, Herstellung und Konformität.",
  },
  {
    id: "q-norm-02",
    type: "true-false",
    category: "Normen",
    difficulty: "Leicht",
    question: "DIN EN ISO/IEC 17025 regelt die Anforderungen an Prüf- und Kalibrierlaboratorien.",
    correctAnswer: true,
    explanation: "DIN EN ISO/IEC 17025 ist die Grundlage für die Akkreditierung von Prüf- und Kalibrierlaboren.",
  },
  {
    id: "q-norm-03",
    type: "multiple-choice",
    category: "Normen",
    difficulty: "Mittel",
    question: "Was bedeutet die CE-Kennzeichnung eines Bauprodukts?",
    options: [
      "Konformität mit den geltenden europäischen Normen",
      "Herstellung ausschließlich in Deutschland",
      "Freiwillige Marketingauszeichnung ohne rechtliche Bedeutung",
      "Bestätigung der günstigsten Marktpreise",
    ],
    correctIndex: 0,
    explanation: "Die CE-Kennzeichnung bestätigt die Konformität eines Bauprodukts mit den geltenden europäischen Normen.",
  },
  {
    id: "q-norm-04",
    type: "true-false",
    category: "Normen",
    difficulty: "Mittel",
    question: "Die Fremdüberwachung erfolgt durch den Hersteller selbst.",
    correctAnswer: false,
    explanation: "Die Eigenüberwachung erfolgt durch den Hersteller, die Fremdüberwachung durch eine unabhängige, akkreditierte Stelle.",
  },
  {
    id: "q-norm-05",
    type: "multiple-choice",
    category: "Normen",
    difficulty: "Schwer",
    question: "Welche Normenreihe regelt Prüfverfahren für Asphalt?",
    options: ["DIN EN 12697", "DIN EN 12390", "DIN 18196", "DIN EN 206"],
    correctIndex: 0,
    explanation: "DIN EN 12697 (Reihe) regelt die Prüfverfahren für Asphalt, u. a. Marshall-Verfahren und Hohlraumgehalt.",
  },
  {
    id: "q-norm-06",
    type: "multiple-choice",
    category: "Normen",
    difficulty: "Mittel",
    question: "Welche Normenreihe regelt die Prüfung von Festbeton?",
    options: ["DIN EN 12390", "DIN EN 12697", "DIN 18122", "DIN EN ISO 17892"],
    correctIndex: 0,
    explanation: "DIN EN 12390 (Reihe) regelt Herstellung, Lagerung und Prüfung von Festbeton-Probekörpern.",
  },
  {
    id: "q-norm-07",
    type: "matching",
    category: "Normen",
    difficulty: "Schwer",
    question: "Ordne jede Norm ihrem Fachbereich zu.",
    pairs: [
      { left: "DIN EN 206", right: "Beton" },
      { left: "DIN EN 12697", right: "Asphalt" },
      { left: "DIN 18196", right: "Geotechnik" },
      { left: "DIN EN ISO/IEC 17025", right: "Labor-Qualitätsmanagement" },
    ],
    explanation: "Jede Norm deckt einen eigenen fachlichen Schwerpunkt der Baustoffprüfung ab.",
  },
];
