import type { Report } from "@/types/report";

// Mocked "heute" passend zu den übrigen Mockdaten dieses Prototyps.
export const HEUTE = "03.03.2026";

export const reports: Report[] = [
  {
    id: "RPT-2026-001",
    titel: "Prüfbericht – Betonwürfel Druckfestigkeit",
    berichtsnummer: "PRB-2026-0457",
    berichtstyp: "Standard-Prüfbericht",
    format: "PDF",
    projekt: "Neubau Wohnanlage Parkblick",
    kunde: "Musterbau GmbH",
    standort: "Labor Stuttgart",
    probeId: "BET-2026-014",
    fachbereich: "Beton",
    pruefer: "Anna Neumann",
    bearbeiter: "Anna Neumann",
    sprache: "Deutsch",
    erstelltAm: "27.02.2026",
    status: "Entwurf",
    pruefungen: [
      { id: "pw-1", name: "Druckfestigkeit – Würfel 1-3", included: true },
      { id: "pw-2", name: "Rohdichte", included: true },
    ],
    fotos: [
      { id: "f-1", title: "Foto Probe.jpg", date: "27.02.2026" },
      { id: "f-2", title: "Foto Bruchbild.jpg", date: "27.02.2026" },
    ],
    dokumente: [{ id: "d-1", title: "Prüfprotokoll.pdf", date: "27.02.2026" }],
    lieferscheine: [{ id: "l-1", title: "LS-2026-001 Betonlieferung", date: "20.01.2026" }],
    bemerkungen: "Beton zeigt eine gleichmäßige Struktur. Keine Auffälligkeiten beim Bruchbild.",
    unterschriften: [
      { rolle: "Prüfer", name: "Anna Neumann", signiert: false },
      { rolle: "Laborleiter", name: "T. Keller", signiert: false },
      { rolle: "Freigabe", name: "—", signiert: false },
    ],
    historie: [{ message: "Bericht angelegt.", timestamp: "27.02.2026" }],
  },
  {
    id: "RPT-2026-002",
    titel: "Prüfbericht – Asphalt Marshall",
    berichtsnummer: "PRB-2026-0458",
    berichtstyp: "Laborbericht",
    format: "PDF",
    projekt: "L 342 Fahrbahnerneuerung",
    kunde: "Straßenbau Nord",
    standort: "Labor Remseck",
    probeId: "ASP-2026-011",
    fachbereich: "Asphalt",
    pruefer: "S. Wolf",
    bearbeiter: "S. Wolf",
    sprache: "Englisch",
    erstelltAm: "25.02.2026",
    status: "Fertig",
    pruefungen: [{ id: "pw-3", name: "Marshall-Prüfung", included: true }],
    fotos: [{ id: "f-3", title: "Foto Probekörper.jpg", date: "25.02.2026" }],
    dokumente: [{ id: "d-2", title: "Prüfprotokoll.pdf", date: "26.02.2026" }],
    lieferscheine: [{ id: "l-2", title: "LS-2026-003 Asphaltmischgut", date: "24.02.2026" }],
    bemerkungen: "Stabilität und Fließwert im Zielbereich.",
    unterschriften: [
      { rolle: "Prüfer", name: "S. Wolf", signiert: true },
      { rolle: "Laborleiter", name: "T. Keller", signiert: true },
      { rolle: "Freigabe", name: "Anna Neumann", signiert: false },
    ],
    historie: [
      { message: "Bericht angelegt.", timestamp: "25.02.2026" },
      { message: "Als fertig markiert.", timestamp: "26.02.2026" },
    ],
  },
  {
    id: "RPT-2026-003",
    titel: "Prüfbericht – Bodenprobe Proctor",
    berichtsnummer: "PRB-2026-0412",
    berichtstyp: "Prüfprotokoll",
    format: "PDF",
    projekt: "Baugebiet Nord",
    kunde: "Musterbau GmbH",
    standort: "Labor Stuttgart",
    probeId: "GEO-2026-021",
    fachbereich: "Geotechnik",
    pruefer: "A. Meier",
    bearbeiter: "A. Meier",
    sprache: "Deutsch",
    erstelltAm: "20.02.2026",
    status: "PDF exportiert",
    pruefungen: [
      { id: "pw-4", name: "Proctorversuch", included: true },
      { id: "pw-5", name: "Wassergehalt", included: true },
    ],
    fotos: [],
    dokumente: [
      { id: "d-3", title: "Prüfprotokoll.pdf", date: "21.02.2026" },
      { id: "d-4", title: "Laborbericht.pdf", date: "21.02.2026" },
    ],
    lieferscheine: [],
    bemerkungen: "Verdichtungsgrad knapp unter Anforderung – Nachverdichtung empfohlen.",
    unterschriften: [
      { rolle: "Prüfer", name: "A. Meier", signiert: true },
      { rolle: "Laborleiter", name: "T. Keller", signiert: true },
      { rolle: "Freigabe", name: "Anna Neumann", signiert: true },
    ],
    historie: [
      { message: "Bericht angelegt.", timestamp: "20.02.2026" },
      { message: "Als fertig markiert.", timestamp: "21.02.2026" },
      { message: "Als PDF exportiert.", timestamp: "21.02.2026" },
    ],
  },
  {
    id: "RPT-2026-004",
    titel: "Prüfbericht – Betonprisma Biegezug",
    berichtsnummer: "PRB-2026-0461",
    berichtstyp: "Standard-Prüfbericht",
    format: "PDF & Excel",
    projekt: "Brückensanierung B17",
    kunde: "Baresel AG",
    standort: "Labor Stuttgart",
    probeId: "PR-2026-008",
    fachbereich: "Beton",
    pruefer: "T. Keller",
    bearbeiter: "T. Keller",
    sprache: "Deutsch",
    erstelltAm: HEUTE,
    status: "Entwurf",
    pruefungen: [{ id: "pw-6", name: "Biegezug", included: true }],
    fotos: [],
    dokumente: [],
    lieferscheine: [],
    bemerkungen: "",
    unterschriften: [
      { rolle: "Prüfer", name: "T. Keller", signiert: false },
      { rolle: "Laborleiter", name: "T. Keller", signiert: false },
      { rolle: "Freigabe", name: "—", signiert: false },
    ],
    historie: [{ message: "Bericht angelegt.", timestamp: HEUTE }],
  },
  {
    id: "RPT-2026-005",
    titel: "Prüfbericht – Asphaltmischgut Sieblinie",
    berichtsnummer: "PRB-2026-0459",
    berichtstyp: "Kompaktbericht",
    format: "Excel",
    projekt: "L 342 Fahrbahnerneuerung",
    kunde: "Straßenbau Nord",
    standort: "Labor Remseck",
    probeId: "ASP-2026-044",
    fachbereich: "Asphalt",
    pruefer: "S. Wolf",
    bearbeiter: "S. Wolf",
    sprache: "Deutsch",
    erstelltAm: "01.03.2026",
    status: "Fertig",
    pruefungen: [{ id: "pw-7", name: "Sieblinie", included: true }],
    fotos: [{ id: "f-4", title: "Foto Mischgut.jpg", date: "01.03.2026" }],
    dokumente: [{ id: "d-5", title: "Prüfprotokoll.pdf", date: "01.03.2026" }],
    lieferscheine: [],
    bemerkungen: "Sieblinie liegt innerhalb des zulässigen Bandes.",
    unterschriften: [
      { rolle: "Prüfer", name: "S. Wolf", signiert: true },
      { rolle: "Laborleiter", name: "T. Keller", signiert: false },
      { rolle: "Freigabe", name: "—", signiert: false },
    ],
    historie: [
      { message: "Bericht angelegt.", timestamp: "01.03.2026" },
      { message: "Als fertig markiert.", timestamp: "02.03.2026" },
    ],
  },
  {
    id: "RPT-2026-006",
    titel: "Prüfbericht – Bodenprobe Wassergehalt",
    berichtsnummer: "PRB-2026-0413",
    berichtstyp: "Baustellenbericht",
    format: "PDF",
    projekt: "Baugebiet Nord",
    kunde: "Musterbau GmbH",
    standort: "Labor Stuttgart",
    probeId: "GEO-2026-033",
    fachbereich: "Geotechnik",
    pruefer: "A. Meier",
    bearbeiter: "A. Meier",
    sprache: "Deutsch",
    erstelltAm: "01.03.2026",
    status: "Entwurf",
    pruefungen: [{ id: "pw-8", name: "Wassergehalt", included: true }],
    fotos: [],
    dokumente: [],
    lieferscheine: [],
    bemerkungen: "",
    unterschriften: [
      { rolle: "Prüfer", name: "A. Meier", signiert: false },
      { rolle: "Laborleiter", name: "T. Keller", signiert: false },
      { rolle: "Freigabe", name: "—", signiert: false },
    ],
    historie: [{ message: "Bericht angelegt.", timestamp: "01.03.2026" }],
  },
  {
    id: "RPT-2026-007",
    titel: "Sammelbericht – Betonwürfel Q1 2026",
    berichtsnummer: "PRB-2026-0301",
    berichtstyp: "Kundenbericht",
    format: "Excel",
    projekt: "Neubau Wohnanlage Parkblick",
    kunde: "Musterbau GmbH",
    standort: "Labor Stuttgart",
    probeId: "BET-2026-022",
    fachbereich: "Beton",
    pruefer: "Anna Neumann",
    bearbeiter: "Anna Neumann",
    sprache: "Deutsch",
    erstelltAm: "15.02.2026",
    status: "Excel exportiert",
    pruefungen: [
      { id: "pw-9", name: "Druckfestigkeit – Sammelauswertung", included: true },
      { id: "pw-10", name: "Rohdichte – Sammelauswertung", included: true },
    ],
    fotos: [{ id: "f-5", title: "Foto Serie.jpg", date: "15.02.2026" }],
    dokumente: [{ id: "d-6", title: "Sammelbericht.pdf", date: "16.02.2026" }],
    lieferscheine: [
      { id: "l-3", title: "LS-2026-001 Betonlieferung", date: "20.01.2026" },
      { id: "l-4", title: "LS-2026-002 Zusatzmittel", date: "28.01.2026" },
    ],
    bemerkungen: "Quartalsauswertung aller Betonwürfel-Prüfungen für das Projekt.",
    unterschriften: [
      { rolle: "Prüfer", name: "Anna Neumann", signiert: true },
      { rolle: "Laborleiter", name: "T. Keller", signiert: true },
      { rolle: "Freigabe", name: "Anna Neumann", signiert: true },
    ],
    historie: [
      { message: "Bericht angelegt.", timestamp: "15.02.2026" },
      { message: "Als fertig markiert.", timestamp: "16.02.2026" },
      { message: "Als Excel exportiert.", timestamp: "16.02.2026" },
    ],
  },
  {
    id: "RPT-2026-008",
    titel: "Prüfbericht – Betonprisma C25/30",
    berichtsnummer: "PRB-2026-0244",
    berichtstyp: "Standard-Prüfbericht",
    format: "PDF",
    projekt: "Brückensanierung B17",
    kunde: "Baresel AG",
    standort: "Labor Stuttgart",
    probeId: "PR-2026-055",
    fachbereich: "Beton",
    pruefer: "T. Keller",
    bearbeiter: "T. Keller",
    sprache: "Deutsch",
    erstelltAm: "27.01.2026",
    status: "Archiviert",
    pruefungen: [{ id: "pw-11", name: "Biegezug", included: true }],
    fotos: [],
    dokumente: [{ id: "d-7", title: "Prüfprotokoll.pdf", date: "28.01.2026" }],
    lieferscheine: [],
    bemerkungen: "Abgeschlossen und archiviert nach Projektabschluss.",
    unterschriften: [
      { rolle: "Prüfer", name: "T. Keller", signiert: true },
      { rolle: "Laborleiter", name: "T. Keller", signiert: true },
      { rolle: "Freigabe", name: "Anna Neumann", signiert: true },
    ],
    historie: [
      { message: "Bericht angelegt.", timestamp: "27.01.2026" },
      { message: "Als fertig markiert.", timestamp: "28.01.2026" },
      { message: "Als PDF exportiert.", timestamp: "28.01.2026" },
      { message: "Bericht archiviert.", timestamp: "15.02.2026" },
    ],
  },
];
