import type { Sample } from "@/types/sample";

export const samples: Sample[] = [
  {
    id: "BET-2026-014",
    bezeichnung: "Beton C25/30",
    fachbereich: "Beton",
    pruefverfahren: "28-Tage-Prüfung",
    kunde: "Musterbau GmbH",
    projekt: "Neubau Wohnanlage",
    entnahmedatum: "03.02.2026",
    pruefdatum: "03.03.2026",
    pruefalter: "28 Tage",
    status: "In Prüfung",
    pruefer: "A. Meier",
  },
  {
    id: "PR-2026-008",
    bezeichnung: "Betonprisma",
    fachbereich: "Beton",
    pruefverfahren: "7-Tage-Prüfung",
    kunde: "Baresel AG",
    projekt: "Brückensanierung B17",
    entnahmedatum: "24.02.2026",
    pruefdatum: "03.03.2026",
    pruefalter: "7 Tage",
    status: "Vorbereitung",
    pruefer: "T. Keller",
  },
  {
    id: "ASP-2026-011",
    bezeichnung: "Asphaltbohrkern",
    fachbereich: "Asphalt",
    pruefverfahren: "Marshall-Prüfung",
    kunde: "Straßenbau Nord",
    projekt: "L 342 Fahrbahnerneuerung",
    entnahmedatum: "25.02.2026",
    pruefdatum: "04.03.2026",
    pruefalter: "7 Tage",
    status: "In Prüfung",
    pruefer: "S. Wolf",
  },
  {
    id: "GEO-2026-021",
    bezeichnung: "Bodenprobe Sand",
    fachbereich: "Geotechnik",
    pruefverfahren: "Proctor-Versuch",
    kunde: "Musterbau GmbH",
    projekt: "Baugebiet Nord",
    entnahmedatum: "18.02.2026",
    pruefdatum: "27.02.2026",
    pruefalter: "eigenes Prüfdatum",
    status: "Überfällig",
    pruefer: "A. Meier",
  },
  {
    id: "ASP-2026-007",
    bezeichnung: "Asphaltmischgut",
    fachbereich: "Asphalt",
    pruefverfahren: "Sieblinie",
    kunde: "Straßenbau Nord",
    projekt: "L 342 Fahrbahnerneuerung",
    entnahmedatum: "20.02.2026",
    pruefdatum: "28.02.2026",
    pruefalter: "7 Tage",
    status: "Abgeschlossen",
    pruefer: "S. Wolf",
  },
  {
    id: "BET-2025-098",
    bezeichnung: "Beton C30/37",
    fachbereich: "Beton",
    pruefverfahren: "28-Tage-Prüfung",
    kunde: "Musterbau GmbH",
    projekt: "Neubau Wohnanlage",
    entnahmedatum: "02.12.2025",
    pruefdatum: "30.12.2025",
    pruefalter: "28 Tage",
    status: "Archiviert",
    pruefer: "T. Keller",
  },
];
