import type { Sample } from "@/types/sample";

// Mock-Daten für den Probenmanager (/probekoerper). Eigenständiger
// Datensatz, keine Firebase-Anbindung. Kunden/Projekte bewusst konsistent
// mit config/customers.ts und config/projects.ts gehalten.

export const samples: Sample[] = [
  {
    id: "BET-2026-014",
    bezeichnung: "Beton C25/30",
    fachbereich: "Beton",
    probenart: "Würfel",
    pruefverfahren: "28-Tage-Prüfung",
    kunde: "Musterbau GmbH",
    projekt: "Neubau Wohnanlage Parkblick",
    standort: "Labor Stuttgart",
    entnahmedatum: "03.02.2026",
    pruefdatum: "03.03.2026",
    pruefalter: "28 Tage",
    status: "In Prüfung",
    pruefer: "A. Meier",
    qrCode: true,
    pruefungen: [
      { id: "pw-1", name: "Druckfestigkeit", status: "In Prüfung", faelligkeitsdatum: "03.03.2026", pruefer: "A. Meier" },
      { id: "pw-2", name: "Rohdichte", status: "Abgeschlossen", faelligkeitsdatum: "03.02.2026", pruefer: "A. Meier" },
    ],
    anhaenge: [
      { id: "anh-1", title: "Foto Probe", date: "03.02.2026" },
      { id: "anh-2", title: "Foto Bruchbild", date: "03.03.2026" },
    ],
    dokumente: [{ id: "doc-1", title: "Prüfprotokoll.pdf", date: "03.03.2026" }],
    lieferscheine: [
      { id: "ls-1", title: "LS-2026-001 Betonlieferung", date: "20.01.2026" },
      { id: "ls-2", title: "LS-2026-002 Zusatzmittel", date: "28.01.2026" },
    ],
    historie: [
      { message: "Probe entnommen.", timestamp: "03.02.2026" },
      { message: "Prüfung gestartet.", timestamp: "03.03.2026" },
    ],
  },
  {
    id: "PR-2026-008",
    bezeichnung: "Betonprisma",
    fachbereich: "Beton",
    probenart: "Prisma",
    pruefverfahren: "7-Tage-Prüfung",
    kunde: "Baresel AG",
    projekt: "Brückensanierung B17",
    standort: "Labor Stuttgart",
    entnahmedatum: "24.02.2026",
    pruefdatum: "03.03.2026",
    pruefalter: "7 Tage",
    status: "Vorbereitung",
    pruefer: "T. Keller",
    pruefungen: [
      { id: "pw-3", name: "Biegezug", status: "Offen", faelligkeitsdatum: "03.03.2026", pruefer: "T. Keller" },
      { id: "pw-4", name: "Druckfestigkeit", status: "Offen", faelligkeitsdatum: "03.03.2026", pruefer: "T. Keller" },
    ],
    anhaenge: [{ id: "anh-3", title: "Foto Probe", date: "24.02.2026" }],
    dokumente: [],
    lieferscheine: [],
    historie: [{ message: "Probe entnommen.", timestamp: "24.02.2026" }],
  },
  {
    id: "ASP-2026-011",
    bezeichnung: "Asphaltbohrkern",
    fachbereich: "Asphalt",
    probenart: "Bohrkern",
    pruefverfahren: "Marshall-Prüfung",
    kunde: "Straßenbau Nord",
    projekt: "L 342 Fahrbahnerneuerung",
    standort: "Labor Remseck",
    entnahmedatum: "25.02.2026",
    pruefdatum: "04.03.2026",
    pruefalter: "7 Tage",
    status: "In Prüfung",
    pruefer: "S. Wolf",
    barcode: true,
    pruefungen: [
      { id: "pw-5", name: "Marshall", status: "In Prüfung", faelligkeitsdatum: "04.03.2026", pruefer: "S. Wolf" },
      { id: "pw-6", name: "Rohdichte", status: "Offen", faelligkeitsdatum: "04.03.2026", pruefer: "S. Wolf" },
    ],
    anhaenge: [{ id: "anh-4", title: "Foto Probe", date: "25.02.2026" }],
    dokumente: [],
    lieferscheine: [{ id: "ls-3", title: "LS-2026-003 Asphaltmischgut", date: "24.02.2026" }],
    historie: [
      { message: "Probe entnommen.", timestamp: "25.02.2026" },
      { message: "Prüfung gestartet.", timestamp: "04.03.2026" },
    ],
  },
  {
    id: "GEO-2026-021",
    bezeichnung: "Bodenprobe Sand",
    fachbereich: "Geotechnik",
    probenart: "Boden",
    pruefverfahren: "Proctor-Versuch",
    kunde: "Musterbau GmbH",
    projekt: "Baugebiet Nord",
    standort: "Labor Stuttgart",
    entnahmedatum: "18.02.2026",
    pruefdatum: "27.02.2026",
    pruefalter: "eigenes Prüfdatum",
    status: "Überfällig",
    pruefer: "A. Meier",
    pruefungen: [
      { id: "pw-7", name: "Proctor", status: "In Prüfung", faelligkeitsdatum: "27.02.2026", pruefer: "A. Meier" },
      { id: "pw-8", name: "Wassergehalt", status: "Offen", faelligkeitsdatum: "27.02.2026", pruefer: "A. Meier" },
    ],
    anhaenge: [],
    dokumente: [],
    lieferscheine: [],
    historie: [
      { message: "Probe entnommen.", timestamp: "18.02.2026" },
      { message: "Prüfdatum überschritten.", timestamp: "27.02.2026" },
    ],
  },
  {
    id: "ASP-2026-007",
    bezeichnung: "Asphaltmischgut",
    fachbereich: "Asphalt",
    probenart: "Asphalt",
    pruefverfahren: "Sieblinie",
    kunde: "Straßenbau Nord",
    projekt: "L 342 Fahrbahnerneuerung",
    standort: "Labor Remseck",
    entnahmedatum: "20.02.2026",
    pruefdatum: "28.02.2026",
    pruefalter: "7 Tage",
    status: "Abgeschlossen",
    pruefer: "S. Wolf",
    pruefungen: [
      { id: "pw-9", name: "Sieblinie", status: "Abgeschlossen", faelligkeitsdatum: "28.02.2026", pruefer: "S. Wolf" },
      { id: "pw-10", name: "Dichte", status: "Abgeschlossen", faelligkeitsdatum: "28.02.2026", pruefer: "S. Wolf" },
    ],
    anhaenge: [{ id: "anh-5", title: "Foto Probe", date: "20.02.2026" }],
    dokumente: [
      { id: "doc-2", title: "Prüfprotokoll.pdf", date: "28.02.2026" },
      { id: "doc-3", title: "Laborbericht.pdf", date: "28.02.2026" },
    ],
    lieferscheine: [],
    historie: [
      { message: "Probe entnommen.", timestamp: "20.02.2026" },
      { message: "Alle Prüfungen abgeschlossen.", timestamp: "28.02.2026" },
    ],
  },
  {
    id: "BET-2026-022",
    bezeichnung: "Betonwürfel C30/37",
    fachbereich: "Beton",
    probenart: "Würfel",
    pruefverfahren: "28-Tage-Prüfung",
    kunde: "Musterbau GmbH",
    projekt: "Neubau Wohnanlage Parkblick",
    standort: "Labor Stuttgart",
    entnahmedatum: "02.03.2026",
    pruefdatum: "30.03.2026",
    pruefalter: "28 Tage",
    status: "Offen",
    pruefer: "Anna Neumann",
    pruefungen: [
      { id: "pw-11", name: "Druckfestigkeit", status: "Offen", faelligkeitsdatum: "30.03.2026", pruefer: "Anna Neumann" },
    ],
    anhaenge: [],
    dokumente: [],
    lieferscheine: [],
    historie: [{ message: "Probe angelegt.", timestamp: "02.03.2026" }],
  },
  {
    id: "GEO-2026-033",
    bezeichnung: "Bodenprobe Lehm",
    fachbereich: "Geotechnik",
    probenart: "Boden",
    pruefverfahren: "Wassergehalt",
    kunde: "Musterbau GmbH",
    projekt: "Baugebiet Nord",
    standort: "Labor Stuttgart",
    entnahmedatum: "01.03.2026",
    pruefdatum: "08.03.2026",
    pruefalter: "eigenes Prüfdatum",
    status: "Vorbereitung",
    pruefer: "A. Meier",
    pruefungen: [
      { id: "pw-12", name: "Wassergehalt", status: "Offen", faelligkeitsdatum: "08.03.2026", pruefer: "A. Meier" },
      { id: "pw-13", name: "Dichte", status: "Offen", faelligkeitsdatum: "08.03.2026", pruefer: "A. Meier" },
    ],
    anhaenge: [],
    dokumente: [],
    lieferscheine: [],
    historie: [{ message: "Probe entnommen.", timestamp: "01.03.2026" }],
  },
  {
    id: "ASP-2026-044",
    bezeichnung: "Asphaltmischgut AC 11 DS",
    fachbereich: "Asphalt",
    probenart: "Asphalt",
    pruefverfahren: "Raumdichte",
    kunde: "Straßenbau Nord",
    projekt: "L 342 Fahrbahnerneuerung",
    standort: "Labor Remseck",
    entnahmedatum: "02.03.2026",
    pruefdatum: "09.03.2026",
    pruefalter: "7 Tage",
    status: "Offen",
    pruefer: "S. Wolf",
    pruefungen: [
      { id: "pw-14", name: "Dichte", status: "Offen", faelligkeitsdatum: "09.03.2026", pruefer: "S. Wolf" },
      { id: "pw-15", name: "Luftgehalt", status: "Offen", faelligkeitsdatum: "09.03.2026", pruefer: "S. Wolf" },
    ],
    anhaenge: [],
    dokumente: [],
    lieferscheine: [],
    historie: [{ message: "Probe angelegt.", timestamp: "02.03.2026" }],
  },
  {
    id: "BET-2025-098",
    bezeichnung: "Beton C30/37",
    fachbereich: "Beton",
    probenart: "Würfel",
    pruefverfahren: "28-Tage-Prüfung",
    kunde: "Musterbau GmbH",
    projekt: "Neubau Wohnanlage Parkblick",
    standort: "Labor Stuttgart",
    entnahmedatum: "02.12.2025",
    pruefdatum: "30.12.2025",
    pruefalter: "28 Tage",
    status: "Archiviert",
    pruefer: "T. Keller",
    pruefungen: [
      { id: "pw-16", name: "Druckfestigkeit", status: "Abgeschlossen", faelligkeitsdatum: "30.12.2025", pruefer: "T. Keller" },
    ],
    anhaenge: [],
    dokumente: [{ id: "doc-4", title: "Prüfprotokoll.pdf", date: "30.12.2025" }],
    lieferscheine: [],
    historie: [
      { message: "Probe entnommen.", timestamp: "02.12.2025" },
      { message: "Prüfung abgeschlossen.", timestamp: "30.12.2025" },
      { message: "Probe archiviert.", timestamp: "15.01.2026" },
    ],
  },
  {
    id: "PR-2026-055",
    bezeichnung: "Betonprisma C25/30",
    fachbereich: "Beton",
    probenart: "Prisma",
    pruefverfahren: "Biegezug",
    kunde: "Baresel AG",
    projekt: "Brückensanierung B17",
    standort: "Labor Stuttgart",
    entnahmedatum: "20.02.2026",
    pruefdatum: "27.02.2026",
    pruefalter: "7 Tage",
    status: "Überfällig",
    pruefer: "T. Keller",
    pruefungen: [
      { id: "pw-17", name: "Biegezug", status: "In Prüfung", faelligkeitsdatum: "27.02.2026", pruefer: "T. Keller" },
      { id: "pw-18", name: "Druckfestigkeit", status: "Offen", faelligkeitsdatum: "27.02.2026", pruefer: "T. Keller" },
    ],
    anhaenge: [],
    dokumente: [],
    lieferscheine: [],
    historie: [
      { message: "Probe entnommen.", timestamp: "20.02.2026" },
      { message: "Prüfdatum überschritten.", timestamp: "27.02.2026" },
    ],
  },
];
